"""CompTIA acronym glossary for practice exams."""
from __future__ import annotations

ACRONYMS_BY_EXAM: dict[str, list[dict[str, str]]] = {
    "comptia-a-plus": [
        {'term': 'BIOS', 'expansion': 'Basic Input/Output System', 'hint': 'Firmware that initializes hardware at boot', 'category': 'Hardware'},
        {'term': 'UEFI', 'expansion': 'Unified Extensible Firmware Interface', 'hint': 'Modern firmware interface replacing legacy BIOS', 'category': 'Hardware'},
        {'term': 'CPU', 'expansion': 'Central Processing Unit', 'hint': 'Primary processor executing instructions', 'category': 'Hardware'},
        {'term': 'GPU', 'expansion': 'Graphics Processing Unit', 'hint': 'Accelerates rendering and parallel compute', 'category': 'Hardware'},
        {'term': 'RAM', 'expansion': 'Random Access Memory', 'hint': 'Volatile memory for active workloads', 'category': 'Hardware'},
        {'term': 'SSD', 'expansion': 'Solid State Drive', 'hint': 'Flash storage without moving parts', 'category': 'Storage'},
        {'term': 'HDD', 'expansion': 'Hard Disk Drive', 'hint': 'Magnetic spinning-platter storage', 'category': 'Storage'},
        {'term': 'NVMe', 'expansion': 'Non-Volatile Memory express', 'hint': 'PCIe protocol for fast SSDs', 'category': 'Storage'},
        {'term': 'SATA', 'expansion': 'Serial Advanced Technology Attachment', 'hint': 'Common drive interface for HDD/SSD', 'category': 'Storage'},
        {'term': 'RAID', 'expansion': 'Redundant Array of Independent Disks', 'hint': 'Combines disks for performance or redundancy', 'category': 'Storage'},
        {'term': 'USB', 'expansion': 'Universal Serial Bus', 'hint': 'Standard peripheral interconnect', 'category': 'Mobile/IO'},
        {'term': 'NFC', 'expansion': 'Near Field Communication', 'hint': 'Short-range contactless communication', 'category': 'Mobile'},
        {'term': 'LCD', 'expansion': 'Liquid Crystal Display', 'hint': 'Flat-panel display technology', 'category': 'Mobile'},
        {'term': 'OLED', 'expansion': 'Organic Light-Emitting Diode', 'hint': 'Self-emissive display with deep blacks', 'category': 'Mobile'},
        {'term': 'Wi-Fi', 'expansion': 'Wireless Fidelity (IEEE 802.11)', 'hint': 'Wireless LAN brand/protocol family', 'category': 'Networking'},
        {'term': 'TCP', 'expansion': 'Transmission Control Protocol', 'hint': 'Connection-oriented transport protocol', 'category': 'Networking'},
        {'term': 'IP', 'expansion': 'Internet Protocol', 'hint': 'Layer 3 addressing and routing', 'category': 'Networking'},
        {'term': 'DNS', 'expansion': 'Domain Name System', 'hint': 'Resolves names to IP addresses', 'category': 'Networking'},
        {'term': 'DHCP', 'expansion': 'Dynamic Host Configuration Protocol', 'hint': 'Automates IP address assignment', 'category': 'Networking'},
        {'term': 'HTTP', 'expansion': 'Hypertext Transfer Protocol', 'hint': 'Web traffic on port 80 by default', 'category': 'Networking'},
        {'term': 'HTTPS', 'expansion': 'HTTP Secure', 'hint': 'HTTP over TLS, port 443', 'category': 'Networking'},
        {'term': 'FTP', 'expansion': 'File Transfer Protocol', 'hint': 'Transfers files, often ports 20/21', 'category': 'Networking'},
        {'term': 'SSH', 'expansion': 'Secure Shell', 'hint': 'Encrypted remote terminal/file access', 'category': 'Networking'},
        {'term': 'RJ-45', 'expansion': 'Registered Jack 45', 'hint': '8P8C connector for Ethernet', 'category': 'Cabling'},
        {'term': 'PoE', 'expansion': 'Power over Ethernet', 'hint': 'Delivers power on Ethernet pairs', 'category': 'Networking'},
        {'term': 'VPN', 'expansion': 'Virtual Private Network', 'hint': 'Encrypted tunnel over public networks', 'category': 'Networking'},
        {'term': 'SSID', 'expansion': 'Service Set Identifier', 'hint': 'Wireless network name', 'category': 'Wireless'},
        {'term': 'WPA2', 'expansion': 'Wi-Fi Protected Access 2', 'hint': 'Wi-Fi security using AES-CCMP', 'category': 'Wireless'},
        {'term': 'ESD', 'expansion': 'Electrostatic Discharge', 'hint': 'Static shock that damages components', 'category': 'Safety'},
        {'term': 'ATX', 'expansion': 'Advanced Technology eXtended', 'hint': 'Common PC motherboard/power form factor', 'category': 'Hardware'},
        {'term': 'POST', 'expansion': 'Power-On Self-Test', 'hint': 'Firmware diagnostics at startup', 'category': 'Troubleshooting'},
        {'term': 'BSOD', 'expansion': 'Blue Screen of Death', 'hint': 'Windows stop error screen', 'category': 'Troubleshooting'},
        {'term': 'APIPA', 'expansion': 'Automatic Private IP Addressing', 'hint': '169.254.x.x self-assigned address', 'category': 'Networking'},
        {'term': 'MAC', 'expansion': 'Media Access Control', 'hint': 'Hardware address on NIC', 'category': 'Networking'},
        {'term': 'IPv4', 'expansion': 'Internet Protocol version 4', 'hint': '32-bit address space', 'category': 'Networking'},
        {'term': 'IPv6', 'expansion': 'Internet Protocol version 6', 'hint': '128-bit address space', 'category': 'Networking'},
        {'term': 'HDMI', 'expansion': 'High-Definition Multimedia Interface', 'hint': 'Audio/video digital connector', 'category': 'Mobile/IO'},
        {'term': 'DisplayPort', 'expansion': 'DisplayPort', 'hint': 'Digital display interface from VESA', 'category': 'Mobile/IO'},
        {'term': 'BYOD', 'expansion': 'Bring Your Own Device', 'hint': 'Personal devices accessing corporate resources', 'category': 'Mobile'},
        {'term': 'MDM', 'expansion': 'Mobile Device Management', 'hint': 'Central policy control for mobile endpoints', 'category': 'Mobile'},
        {'term': 'IaaS', 'expansion': 'Infrastructure as a Service', 'hint': 'Cloud VMs and networks you manage', 'category': 'Cloud'},
        {'term': 'SaaS', 'expansion': 'Software as a Service', 'hint': 'Cloud-hosted applications', 'category': 'Cloud'},
        {'term': 'PaaS', 'expansion': 'Platform as a Service', 'hint': 'Managed runtime for developers', 'category': 'Cloud'},
        {'term': 'VDI', 'expansion': 'Virtual Desktop Infrastructure', 'hint': 'Hosted desktops from datacenter', 'category': 'Virtualization'},
        {'term': 'Hyper-V', 'expansion': 'Microsoft Hyper-V', 'hint': 'Windows Type 1/2 hypervisor', 'category': 'Virtualization'},
        {'term': 'TPM', 'expansion': 'Trusted Platform Module', 'hint': 'Hardware root of trust chip', 'category': 'Security'},
        {'term': 'UEFI Secure Boot', 'expansion': 'Secure Boot', 'hint': 'Validates OS bootloader signatures', 'category': 'Security'},
        {'term': 'LCD inverter', 'expansion': 'Inverter board', 'hint': 'Backlight power for some laptop screens', 'category': 'Mobile'},
        {'term': 'SO-DIMM', 'expansion': 'Small Outline Dual In-Line Memory Module', 'hint': 'Compact RAM form for laptops', 'category': 'Hardware'},
        {'term': 'ECC', 'expansion': 'Error-Correcting Code', 'hint': 'Memory that fixes single-bit errors', 'category': 'Hardware'},
    ],
    "comptia-network-plus": [
        {'term': 'OSI', 'expansion': 'Open Systems Interconnection', 'hint': '7-layer network reference model', 'category': 'Networking'},
        {'term': 'TCP', 'expansion': 'Transmission Control Protocol', 'hint': 'Connection-oriented Layer 4 protocol', 'category': 'Networking'},
        {'term': 'UDP', 'expansion': 'User Datagram Protocol', 'hint': 'Connectionless Layer 4 protocol', 'category': 'Networking'},
        {'term': 'IP', 'expansion': 'Internet Protocol', 'hint': 'Layer 3 logical addressing', 'category': 'Networking'},
        {'term': 'ICMP', 'expansion': 'Internet Control Message Protocol', 'hint': 'Diagnostics like ping/traceroute', 'category': 'Networking'},
        {'term': 'ARP', 'expansion': 'Address Resolution Protocol', 'hint': 'Maps IP to MAC on LAN', 'category': 'Networking'},
        {'term': 'DNS', 'expansion': 'Domain Name System', 'hint': 'Name to IP resolution', 'category': 'Networking'},
        {'term': 'DHCP', 'expansion': 'Dynamic Host Configuration Protocol', 'hint': 'Automated IP configuration', 'category': 'Networking'},
        {'term': 'NAT', 'expansion': 'Network Address Translation', 'hint': 'Translates private to public addresses', 'category': 'Networking'},
        {'term': 'PAT', 'expansion': 'Port Address Translation', 'hint': 'NAT overload using ports', 'category': 'Networking'},
        {'term': 'VLAN', 'expansion': 'Virtual Local Area Network', 'hint': 'Logical LAN segmentation', 'category': 'Switching'},
        {'term': 'STP', 'expansion': 'Spanning Tree Protocol', 'hint': 'Prevents switching loops', 'category': 'Switching'},
        {'term': 'PoE', 'expansion': 'Power over Ethernet', 'hint': 'Power on Ethernet pairs', 'category': 'Infrastructure'},
        {'term': 'QoS', 'expansion': 'Quality of Service', 'hint': 'Prioritizes traffic classes', 'category': 'Networking'},
        {'term': 'MPLS', 'expansion': 'Multiprotocol Label Switching', 'hint': 'Label-switched WAN forwarding', 'category': 'WAN'},
        {'term': 'BGP', 'expansion': 'Border Gateway Protocol', 'hint': 'Inter-domain routing on the internet', 'category': 'Routing'},
        {'term': 'OSPF', 'expansion': 'Open Shortest Path First', 'hint': 'Link-state IGP routing protocol', 'category': 'Routing'},
        {'term': 'RIP', 'expansion': 'Routing Information Protocol', 'hint': 'Distance-vector routing protocol', 'category': 'Routing'},
        {'term': 'VPN', 'expansion': 'Virtual Private Network', 'hint': 'Encrypted tunnel over untrusted networks', 'category': 'Security'},
        {'term': 'IPsec', 'expansion': 'Internet Protocol Security', 'hint': 'Suite securing IP communications', 'category': 'Security'},
        {'term': 'SSL', 'expansion': 'Secure Sockets Layer (legacy name)', 'hint': 'Predecessor terminology for TLS on HTTPS', 'category': 'Security'},
        {'term': 'TLS', 'expansion': 'Transport Layer Security', 'hint': 'Encrypts application traffic', 'category': 'Security'},
        {'term': 'WPA3', 'expansion': 'Wi-Fi Protected Access 3', 'hint': 'Latest Wi-Fi security generation', 'category': 'Wireless'},
        {'term': 'SSID', 'expansion': 'Service Set Identifier', 'hint': 'Wireless network name', 'category': 'Wireless'},
        {'term': 'RF', 'expansion': 'Radio Frequency', 'hint': 'Wireless signal spectrum', 'category': 'Wireless'},
        {'term': 'SNR', 'expansion': 'Signal-to-Noise Ratio', 'hint': 'Wireless signal quality metric', 'category': 'Wireless'},
        {'term': 'MTU', 'expansion': 'Maximum Transmission Unit', 'hint': 'Largest packet size on interface', 'category': 'Networking'},
        {'term': 'CRC', 'expansion': 'Cyclic Redundancy Check', 'hint': 'Error detection in frames', 'category': 'Networking'},
        {'term': 'FCS', 'expansion': 'Frame Check Sequence', 'hint': 'Ethernet trailer error field', 'category': 'Networking'},
        {'term': 'LLDP', 'expansion': 'Link Layer Discovery Protocol', 'hint': 'Neighbor discovery on switches', 'category': 'Operations'},
        {'term': 'SNMP', 'expansion': 'Simple Network Management Protocol', 'hint': 'Monitors network devices', 'category': 'Operations'},
        {'term': 'NTP', 'expansion': 'Network Time Protocol', 'hint': 'Synchronizes clocks', 'category': 'Operations'},
        {'term': 'Syslog', 'expansion': 'System Logging Protocol', 'hint': 'Centralized log messaging', 'category': 'Operations'},
        {'term': 'ACL', 'expansion': 'Access Control List', 'hint': 'Permit/deny traffic rules', 'category': 'Security'},
        {'term': 'DoS', 'expansion': 'Denial of Service', 'hint': 'Availability attack', 'category': 'Security'},
        {'term': 'DDoS', 'expansion': 'Distributed Denial of Service', 'hint': 'DoS from many sources', 'category': 'Security'},
        {'term': 'IDS', 'expansion': 'Intrusion Detection System', 'hint': 'Detects suspicious activity', 'category': 'Security'},
        {'term': 'IPS', 'expansion': 'Intrusion Prevention System', 'hint': 'Blocks detected threats inline', 'category': 'Security'},
        {'term': 'NAC', 'expansion': 'Network Access Control', 'hint': 'Admits compliant endpoints', 'category': 'Security'},
        {'term': '802.1X', 'expansion': 'Port-Based Network Access Control', 'hint': 'Authenticates devices before LAN access', 'category': 'Security'},
        {'term': 'RADIUS', 'expansion': 'Remote Authentication Dial-In User Service', 'hint': 'Central AAA for network access', 'category': 'Security'},
        {'term': 'TACACS+', 'expansion': 'Terminal Access Controller Access-Control System Plus', 'hint': 'Cisco-oriented AAA protocol', 'category': 'Security'},
        {'term': 'SD-WAN', 'expansion': 'Software-Defined WAN', 'hint': 'Policy-based WAN path selection', 'category': 'WAN'},
        {'term': 'ISP', 'expansion': 'Internet Service Provider', 'hint': 'Provides internet connectivity', 'category': 'WAN'},
        {'term': 'CPE', 'expansion': 'Customer Premises Equipment', 'hint': 'Customer-side WAN/router gear', 'category': 'WAN'},
        {'term': 'MTBF', 'expansion': 'Mean Time Between Failures', 'hint': 'Reliability metric', 'category': 'Operations'},
        {'term': 'MTTR', 'expansion': 'Mean Time To Repair/Recover', 'hint': 'Recovery time metric', 'category': 'Operations'},
        {'term': 'SLA', 'expansion': 'Service Level Agreement', 'hint': 'Contracted service expectations', 'category': 'Operations'},
        {'term': 'UPS', 'expansion': 'Uninterruptible Power Supply', 'hint': 'Battery backup for gear', 'category': 'Infrastructure'},
        {'term': 'PDU', 'expansion': 'Power Distribution Unit', 'hint': 'Rack power distribution', 'category': 'Infrastructure'},
    ],
    "comptia-security-plus": [
        {'term': 'CIA', 'expansion': 'Confidentiality, Integrity, Availability', 'hint': 'Core security triad', 'category': 'Concepts'},
        {'term': 'AAA', 'expansion': 'Authentication, Authorization, Accounting', 'hint': 'Access control framework', 'category': 'Concepts'},
        {'term': 'MFA', 'expansion': 'Multi-Factor Authentication', 'hint': 'Two or more auth factors', 'category': 'Identity'},
        {'term': 'SSO', 'expansion': 'Single Sign-On', 'hint': 'One login for multiple apps', 'category': 'Identity'},
        {'term': 'IAM', 'expansion': 'Identity and Access Management', 'hint': 'Manages digital identities', 'category': 'Identity'},
        {'term': 'PKI', 'expansion': 'Public Key Infrastructure', 'hint': 'Certificates and CAs', 'category': 'Cryptography'},
        {'term': 'CA', 'expansion': 'Certificate Authority', 'hint': 'Issues digital certificates', 'category': 'Cryptography'},
        {'term': 'AES', 'expansion': 'Advanced Encryption Standard', 'hint': 'Symmetric encryption standard', 'category': 'Cryptography'},
        {'term': 'RSA', 'expansion': 'Rivest-Shamir-Adleman', 'hint': 'Asymmetric encryption algorithm', 'category': 'Cryptography'},
        {'term': 'ECC', 'expansion': 'Elliptic Curve Cryptography', 'hint': 'Efficient public-key crypto', 'category': 'Cryptography'},
        {'term': 'HMAC', 'expansion': 'Hash-based Message Authentication Code', 'hint': 'Integrity with secret key', 'category': 'Cryptography'},
        {'term': 'SHA', 'expansion': 'Secure Hash Algorithm', 'hint': 'Cryptographic hash family', 'category': 'Cryptography'},
        {'term': 'SSL', 'expansion': 'Secure Sockets Layer', 'hint': 'Legacy term often meaning TLS', 'category': 'Cryptography'},
        {'term': 'TLS', 'expansion': 'Transport Layer Security', 'hint': 'Secures data in transit', 'category': 'Cryptography'},
        {'term': 'VPN', 'expansion': 'Virtual Private Network', 'hint': 'Encrypted remote connectivity', 'category': 'Network Security'},
        {'term': 'IPsec', 'expansion': 'Internet Protocol Security', 'hint': 'Network layer VPN suite', 'category': 'Network Security'},
        {'term': 'NAT', 'expansion': 'Network Address Translation', 'hint': 'Address translation at gateway', 'category': 'Network Security'},
        {'term': 'ACL', 'expansion': 'Access Control List', 'hint': 'Traffic filter rules', 'category': 'Network Security'},
        {'term': 'SIEM', 'expansion': 'Security Information and Event Management', 'hint': 'Log aggregation and correlation', 'category': 'Operations'},
        {'term': 'SOAR', 'expansion': 'Security Orchestration, Automation and Response', 'hint': 'Automates incident workflows', 'category': 'Operations'},
        {'term': 'EDR', 'expansion': 'Endpoint Detection and Response', 'hint': 'Monitors endpoint threats', 'category': 'Operations'},
        {'term': 'XDR', 'expansion': 'Extended Detection and Response', 'hint': 'Cross-domain detection platform', 'category': 'Operations'},
        {'term': 'IDS', 'expansion': 'Intrusion Detection System', 'hint': 'Detects intrusions', 'category': 'Operations'},
        {'term': 'IPS', 'expansion': 'Intrusion Prevention System', 'hint': 'Blocks intrusions inline', 'category': 'Operations'},
        {'term': 'DLP', 'expansion': 'Data Loss Prevention', 'hint': 'Prevents unauthorized data exfil', 'category': 'Operations'},
        {'term': 'NIDS', 'expansion': 'Network IDS', 'hint': 'Monitors network traffic', 'category': 'Operations'},
        {'term': 'HIDS', 'expansion': 'Host IDS', 'hint': 'Monitors individual hosts', 'category': 'Operations'},
        {'term': 'CVE', 'expansion': 'Common Vulnerabilities and Exposures', 'hint': 'Vulnerability identifier', 'category': 'Threats'},
        {'term': 'CVSS', 'expansion': 'Common Vulnerability Scoring System', 'hint': 'Vulnerability severity score', 'category': 'Threats'},
        {'term': 'IOC', 'expansion': 'Indicator of Compromise', 'hint': 'Artifact suggesting breach', 'category': 'Threats'},
        {'term': 'TTP', 'expansion': 'Tactics, Techniques, and Procedures', 'hint': 'Attacker behavior patterns', 'category': 'Threats'},
        {'term': 'APT', 'expansion': 'Advanced Persistent Threat', 'hint': 'Long-term targeted attacker', 'category': 'Threats'},
        {'term': 'MITM', 'expansion': 'Man-in-the-Middle', 'hint': 'Intercepts communications', 'category': 'Threats'},
        {'term': 'DoS', 'expansion': 'Denial of Service', 'hint': 'Disrupts availability', 'category': 'Threats'},
        {'term': 'DDoS', 'expansion': 'Distributed Denial of Service', 'hint': 'DoS from botnet', 'category': 'Threats'},
        {'term': 'XSS', 'expansion': 'Cross-Site Scripting', 'hint': 'Inject scripts into web apps', 'category': 'Threats'},
        {'term': 'CSRF', 'expansion': 'Cross-Site Request Forgery', 'hint': 'Forces authenticated actions', 'category': 'Threats'},
        {'term': 'SQLi', 'expansion': 'SQL Injection', 'hint': 'Manipulates database queries', 'category': 'Threats'},
        {'term': 'RFI', 'expansion': 'Remote File Inclusion', 'hint': 'Includes remote files in web apps', 'category': 'Threats'},
        {'term': 'LFI', 'expansion': 'Local File Inclusion', 'hint': 'Includes local files improperly', 'category': 'Threats'},
        {'term': 'GDPR', 'expansion': 'General Data Protection Regulation', 'hint': 'EU privacy regulation', 'category': 'Governance'},
        {'term': 'HIPAA', 'expansion': 'Health Insurance Portability and Accountability Act', 'hint': 'US healthcare privacy', 'category': 'Governance'},
        {'term': 'PCI DSS', 'expansion': 'Payment Card Industry Data Security Standard', 'hint': 'Card data security standard', 'category': 'Governance'},
        {'term': 'SOC', 'expansion': 'Service Organization Control', 'hint': 'Audit report on controls', 'category': 'Governance'},
        {'term': 'BCP', 'expansion': 'Business Continuity Plan', 'hint': 'Maintains operations during disruption', 'category': 'Governance'},
        {'term': 'DRP', 'expansion': 'Disaster Recovery Plan', 'hint': 'Restores IT after disaster', 'category': 'Governance'},
        {'term': 'RTO', 'expansion': 'Recovery Time Objective', 'hint': 'Max acceptable downtime', 'category': 'Governance'},
        {'term': 'RPO', 'expansion': 'Recovery Point Objective', 'hint': 'Max acceptable data loss window', 'category': 'Governance'},
        {'term': 'MOU', 'expansion': 'Memorandum of Understanding', 'hint': 'Non-binding agreement outline', 'category': 'Governance'},
        {'term': 'NDA', 'expansion': 'Non-Disclosure Agreement', 'hint': 'Protects confidential information', 'category': 'Governance'},
        {'term': 'AUP', 'expansion': 'Acceptable Use Policy', 'hint': 'Defines permitted system use', 'category': 'Governance'},
        {'term': 'RBAC', 'expansion': 'Role-Based Access Control', 'hint': 'Permissions by job role', 'category': 'Architecture'},
        {'term': 'MAC', 'expansion': 'Mandatory Access Control', 'hint': 'Label-based access enforcement', 'category': 'Architecture'},
        {'term': 'DAC', 'expansion': 'Discretionary Access Control', 'hint': 'Owner decides access', 'category': 'Architecture'},
        {'term': 'ABAC', 'expansion': 'Attribute-Based Access Control', 'hint': 'Policies on attributes', 'category': 'Architecture'},
    ],
    "comptia-cysa-plus": [
        {'term': 'SOC', 'expansion': 'Security Operations Center', 'hint': 'Team monitoring security events', 'category': 'Operations'},
        {'term': 'SIEM', 'expansion': 'Security Information and Event Management', 'hint': 'Central log correlation', 'category': 'Operations'},
        {'term': 'SOAR', 'expansion': 'Security Orchestration, Automation and Response', 'hint': 'Automates response playbooks', 'category': 'Operations'},
        {'term': 'EDR', 'expansion': 'Endpoint Detection and Response', 'hint': 'Endpoint telemetry and response', 'category': 'Operations'},
        {'term': 'XDR', 'expansion': 'Extended Detection and Response', 'hint': 'Unified detection across domains', 'category': 'Operations'},
        {'term': 'UEBA', 'expansion': 'User and Entity Behavior Analytics', 'hint': 'Detects anomalous behavior', 'category': 'Operations'},
        {'term': 'IOC', 'expansion': 'Indicator of Compromise', 'hint': 'Sign of potential intrusion', 'category': 'Operations'},
        {'term': 'TTP', 'expansion': 'Tactics, Techniques, and Procedures', 'hint': 'Adversary behavior model', 'category': 'Operations'},
        {'term': 'MITRE ATT&CK', 'expansion': 'Adversarial Tactics, Techniques, and Common Knowledge', 'hint': 'ATT&CK knowledge base', 'category': 'Operations'},
        {'term': 'YARA', 'expansion': 'Yet Another Recursive Acronym', 'hint': 'Pattern matching for malware', 'category': 'Operations'},
        {'term': 'STIX', 'expansion': 'Structured Threat Information Expression', 'hint': 'Threat intel format', 'category': 'Operations'},
        {'term': 'TAXII', 'expansion': 'Trusted Automated Exchange of Intelligence Information', 'hint': 'Transports threat intel', 'category': 'Operations'},
        {'term': 'CVSS', 'expansion': 'Common Vulnerability Scoring System', 'hint': 'Vulnerability severity scoring', 'category': 'Vulnerability'},
        {'term': 'CVE', 'expansion': 'Common Vulnerabilities and Exposures', 'hint': 'Public vulnerability ID', 'category': 'Vulnerability'},
        {'term': 'CPE', 'expansion': 'Common Platform Enumeration', 'hint': 'Standardized platform naming', 'category': 'Vulnerability'},
        {'term': 'CWE', 'expansion': 'Common Weakness Enumeration', 'hint': 'Software weakness categories', 'category': 'Vulnerability'},
        {'term': 'NVD', 'expansion': 'National Vulnerability Database', 'hint': 'US CVE repository', 'category': 'Vulnerability'},
        {'term': 'VM', 'expansion': 'Vulnerability Management', 'hint': 'Lifecycle of finding/fixing flaws', 'category': 'Vulnerability'},
        {'term': 'PT', 'expansion': 'Penetration Test', 'hint': 'Authorized simulated attack', 'category': 'Vulnerability'},
        {'term': 'DAST', 'expansion': 'Dynamic Application Security Testing', 'hint': 'Tests running web apps', 'category': 'Vulnerability'},
        {'term': 'SAST', 'expansion': 'Static Application Security Testing', 'hint': 'Analyzes source code', 'category': 'Vulnerability'},
        {'term': 'SCA', 'expansion': 'Software Composition Analysis', 'hint': 'Scans third-party components', 'category': 'Vulnerability'},
        {'term': 'WAF', 'expansion': 'Web Application Firewall', 'hint': 'Filters HTTP traffic to apps', 'category': 'Vulnerability'},
        {'term': 'CASB', 'expansion': 'Cloud Access Security Broker', 'hint': 'Monitors cloud app use', 'category': 'Operations'},
        {'term': 'DNS', 'expansion': 'Domain Name System', 'hint': 'Name resolution protocol', 'category': 'Operations'},
        {'term': 'PCAP', 'expansion': 'Packet Capture', 'hint': 'Recorded network traffic', 'category': 'Operations'},
        {'term': 'NetFlow', 'expansion': 'Network Flow Export', 'hint': 'Metadata about conversations', 'category': 'Operations'},
        {'term': 'TLS', 'expansion': 'Transport Layer Security', 'hint': 'Encrypts traffic in transit', 'category': 'Operations'},
        {'term': 'JA3', 'expansion': 'TLS Client Fingerprint Hash', 'hint': 'Fingerprints TLS clients', 'category': 'Operations'},
        {'term': 'IR', 'expansion': 'Incident Response', 'hint': 'Process handling security incidents', 'category': 'Incident'},
        {'term': 'PIR', 'expansion': 'Post-Incident Review', 'hint': 'After-action report', 'category': 'Incident'},
        {'term': 'RFI', 'expansion': 'Request for Information', 'hint': 'Gathers vendor/security info', 'category': 'Reporting'},
        {'term': 'KPI', 'expansion': 'Key Performance Indicator', 'hint': 'Measures program effectiveness', 'category': 'Reporting'},
        {'term': 'KRI', 'expansion': 'Key Risk Indicator', 'hint': 'Early warning risk metric', 'category': 'Reporting'},
        {'term': 'MTTD', 'expansion': 'Mean Time To Detect', 'hint': 'Average detection delay', 'category': 'Reporting'},
        {'term': 'MTTR', 'expansion': 'Mean Time To Respond/Recover', 'hint': 'Average response/recovery time', 'category': 'Reporting'},
        {'term': 'SLA', 'expansion': 'Service Level Agreement', 'hint': 'Service expectation contract', 'category': 'Reporting'},
        {'term': 'GDPR', 'expansion': 'General Data Protection Regulation', 'hint': 'EU data protection law', 'category': 'Reporting'},
        {'term': 'HIPAA', 'expansion': 'Health Insurance Portability and Accountability Act', 'hint': 'US health data rules', 'category': 'Reporting'},
        {'term': 'PCI DSS', 'expansion': 'Payment Card Industry Data Security Standard', 'hint': 'Cardholder data standard', 'category': 'Reporting'},
        {'term': 'FOIA', 'expansion': 'Freedom of Information Act', 'hint': 'US public records law', 'category': 'Reporting'},
        {'term': 'Chain of Custody', 'expansion': 'Evidence handling record', 'hint': 'Documents evidence control', 'category': 'Incident'},
        {'term': 'DFIR', 'expansion': 'Digital Forensics and Incident Response', 'hint': 'Forensics plus IR discipline', 'category': 'Incident'},
        {'term': 'RAM', 'expansion': 'Random Access Memory', 'hint': 'Volatile memory for forensics', 'category': 'Incident'},
        {'term': 'SSD', 'expansion': 'Solid State Drive', 'hint': 'Non-volatile storage imaging', 'category': 'Incident'},
        {'term': 'E01', 'expansion': 'Expert Witness Format', 'hint': 'Forensic disk image format', 'category': 'Incident'},
        {'term': 'CSV', 'expansion': 'Comma-Separated Values', 'hint': 'Common export for reporting', 'category': 'Reporting'},
        {'term': 'JSON', 'expansion': 'JavaScript Object Notation', 'hint': 'Structured data interchange', 'category': 'Reporting'},
        {'term': 'API', 'expansion': 'Application Programming Interface', 'hint': 'Programmatic integration', 'category': 'Operations'},
        {'term': 'IAM', 'expansion': 'Identity and Access Management', 'hint': 'Cloud identity controls', 'category': 'Operations'},
    ],
    "comptia-linux-plus": [
        {'term': 'CLI', 'expansion': 'Command Line Interface', 'hint': 'Text-based shell control', 'category': 'Management'},
        {'term': 'GUI', 'expansion': 'Graphical User Interface', 'hint': 'Visual desktop environment', 'category': 'Management'},
        {'term': 'SSH', 'expansion': 'Secure Shell', 'hint': 'Encrypted remote administration', 'category': 'Security'},
        {'term': 'SFTP', 'expansion': 'SSH File Transfer Protocol', 'hint': 'Secure file transfer over SSH', 'category': 'Security'},
        {'term': 'SCP', 'expansion': 'Secure Copy Protocol', 'hint': 'Copy files over SSH', 'category': 'Security'},
        {'term': 'sudo', 'expansion': 'SuperUser DO', 'hint': 'Runs commands as root with policy', 'category': 'Security'},
        {'term': 'PAM', 'expansion': 'Pluggable Authentication Modules', 'hint': 'Linux authentication framework', 'category': 'Security'},
        {'term': 'SELinux', 'expansion': 'Security-Enhanced Linux', 'hint': 'Mandatory access control on Linux', 'category': 'Security'},
        {'term': 'AppArmor', 'expansion': 'Application Armor', 'hint': 'Path-based MAC on Linux', 'category': 'Security'},
        {'term': 'ACL', 'expansion': 'Access Control List', 'hint': 'Fine-grained POSIX permissions', 'category': 'Security'},
        {'term': 'UID', 'expansion': 'User Identifier', 'hint': 'Numeric user ID', 'category': 'Management'},
        {'term': 'GID', 'expansion': 'Group Identifier', 'hint': 'Numeric group ID', 'category': 'Management'},
        {'term': 'PID', 'expansion': 'Process Identifier', 'hint': 'Unique process number', 'category': 'Management'},
        {'term': 'PPID', 'expansion': 'Parent Process Identifier', 'hint': 'PID of parent process', 'category': 'Management'},
        {'term': 'systemd', 'expansion': 'System Daemon', 'hint': 'Init and service manager', 'category': 'Management'},
        {'term': 'GRUB', 'expansion': 'GRand Unified Bootloader', 'hint': 'Boot loader on many distros', 'category': 'Management'},
        {'term': 'UEFI', 'expansion': 'Unified Extensible Firmware Interface', 'hint': 'Modern firmware interface', 'category': 'Management'},
        {'term': 'LVM', 'expansion': 'Logical Volume Manager', 'hint': 'Flexible disk volume management', 'category': 'Storage'},
        {'term': 'PV', 'expansion': 'Physical Volume', 'hint': 'LVM disk component', 'category': 'Storage'},
        {'term': 'VG', 'expansion': 'Volume Group', 'hint': 'LVM pool of PVs', 'category': 'Storage'},
        {'term': 'LV', 'expansion': 'Logical Volume', 'hint': 'LVM formatted volume', 'category': 'Storage'},
        {'term': 'RAID', 'expansion': 'Redundant Array of Independent Disks', 'hint': 'Disk redundancy/performance', 'category': 'Storage'},
        {'term': 'EXT4', 'expansion': 'Fourth Extended Filesystem', 'hint': 'Common Linux filesystem', 'category': 'Storage'},
        {'term': 'XFS', 'expansion': 'X File System', 'hint': 'High-performance journaling FS', 'category': 'Storage'},
        {'term': 'Btrfs', 'expansion': 'B-Tree File System', 'hint': 'Copy-on-write filesystem', 'category': 'Storage'},
        {'term': 'NFS', 'expansion': 'Network File System', 'hint': 'Remote file sharing protocol', 'category': 'Storage'},
        {'term': 'CIFS', 'expansion': 'Common Internet File System', 'hint': 'SMB file sharing protocol', 'category': 'Storage'},
        {'term': 'cron', 'expansion': 'Chronograph (scheduled jobs)', 'hint': 'Time-based job scheduler', 'category': 'Automation'},
        {'term': 'at', 'expansion': 'At (scheduled once)', 'hint': 'One-time job scheduler', 'category': 'Automation'},
        {'term': 'YAML', 'expansion': "YAML Ain't Markup Language", 'hint': 'Data format for Ansible/K8s', 'category': 'Automation'},
        {'term': 'JSON', 'expansion': 'JavaScript Object Notation', 'hint': 'Structured config/data format', 'category': 'Automation'},
        {'term': 'Git', 'expansion': 'Global Information Tracker', 'hint': 'Distributed version control', 'category': 'Automation'},
        {'term': 'CI/CD', 'expansion': 'Continuous Integration/Continuous Delivery', 'hint': 'Automated build/deploy pipeline', 'category': 'Automation'},
        {'term': 'Docker', 'expansion': 'Container runtime platform', 'hint': 'Packages apps in containers', 'category': 'Automation'},
        {'term': 'Podman', 'expansion': 'Pod Manager', 'hint': 'Daemonless container engine', 'category': 'Automation'},
        {'term': 'Kubernetes', 'expansion': 'K8s container orchestrator', 'hint': 'Orchestrates container workloads', 'category': 'Automation'},
        {'term': 'kubectl', 'expansion': 'Kubernetes control CLI', 'hint': 'CLI for Kubernetes API', 'category': 'Automation'},
        {'term': 'Ansible', 'expansion': 'Automation engine', 'hint': 'Agentless configuration management', 'category': 'Automation'},
        {'term': 'Terraform', 'expansion': 'Infrastructure as Code tool', 'hint': 'Provisions cloud resources', 'category': 'Automation'},
        {'term': 'bash', 'expansion': 'Bourne Again SHell', 'hint': 'Common Linux shell', 'category': 'Automation'},
        {'term': 'shebang', 'expansion': '#! interpreter line', 'hint': 'Script interpreter directive', 'category': 'Automation'},
        {'term': 'APT', 'expansion': 'Advanced Package Tool', 'hint': 'Debian/Ubuntu package manager', 'category': 'Management'},
        {'term': 'DNF', 'expansion': 'Dandified YUM', 'hint': 'Fedora/RHEL package manager', 'category': 'Management'},
        {'term': 'RPM', 'expansion': 'Red Hat Package Manager', 'hint': 'Package format on RHEL family', 'category': 'Management'},
        {'term': 'journald', 'expansion': 'Systemd journal daemon', 'hint': 'Binary system logging', 'category': 'Troubleshooting'},
        {'term': 'dmesg', 'expansion': 'Display message', 'hint': 'Kernel ring buffer messages', 'category': 'Troubleshooting'},
        {'term': 'strace', 'expansion': 'System call trace', 'hint': 'Traces process syscalls', 'category': 'Troubleshooting'},
        {'term': 'tcpdump', 'expansion': 'TCP dump', 'hint': 'Captures network packets', 'category': 'Troubleshooting'},
        {'term': 'iptables', 'expansion': 'IP tables firewall', 'hint': 'Legacy netfilter frontend', 'category': 'Security'},
        {'term': 'nftables', 'expansion': 'Netfilter tables', 'hint': 'Modern netfilter framework', 'category': 'Security'},
        {'term': 'firewalld', 'expansion': 'Dynamic firewall daemon', 'hint': 'Zone-based firewall on RHEL', 'category': 'Security'},
        {'term': 'GPG', 'expansion': 'GNU Privacy Guard', 'hint': 'Encryption and signing tool', 'category': 'Security'},
    ],
}
