"""Core learning objectives per Key Training sub-domain (shown after certification exams)."""

DOMAIN_CONCEPTS: dict[str, str] = {
    "authentication": "Verify identity with strong, phishing-resistant methods and respond to impossible-travel and lockout patterns.",
    "mfa": "Multi-factor authentication must resist bypass (SIM swap, MFA fatigue) and protect privileged access.",
    "privilege-escalation": "Limit paths to higher privileges in OS, cloud IAM, and Kerberos/AD misconfigurations.",
    "account-misuse": "Joiner-mover-leaver and access reviews prevent stale, shared, and orphaned accounts.",
    "credential-abuse": "Assume breached passwords: reset, revoke sessions, scan repos, and detect password spray.",
    "phishing": "Contain look-alike domains and user-reported phish; layer beyond link blocking (vishing, quishing).",
    "spoofing": "Email authenticity uses SPF/DKIM/DMARC alignment; display-name spoofing needs banners and verification.",
    "malicious-attachments": "Treat weaponized Office/PDF/archive attachments with sandboxing, not user execution.",
    "bec": "Wire and payment changes require out-of-band verification and vendor domain controls.",
    "sensitive-exposure": "Classify data, block public exposure, and trigger breach workflows for regulated data.",
    "encryption": "Protect data at rest and in transit; weak TLS and unencrypted backups expand blast radius.",
    "dlp": "Control exfil channels (email, USB, GenAI paste) with tuned policies and approved tools.",
    "removable-media": "Unknown USB and MTP devices are untrusted; analyze only in isolated sandboxes.",
    "backups": "Immutable, offline, and tested backups survive ransomware; co-located copies often fail.",
    "malware": "Investigate signed-but-anomalous binaries and restrict unapproved software installation.",
    "ransomware": "Isolate, preserve evidence, and restore from clean backups before negotiating payment.",
    "process-analysis": "Parent/child process chains reveal LOLBins, injection, and suspicious network children.",
    "persistence": "Startup items, scheduled tasks, and services maintain access after reboot.",
    "av-status": "AV/EDR must stay enabled, updated, and centrally monitored—not disabled for convenience.",
    "ids-ips": "Tune alerts to context; correlate IDS events with endpoints and identity logs.",
    "port-anomalies": "Unexpected listening ports and outbound connections may indicate C2 or lateral movement.",
    "beaconing": "Regular low-volume callbacks suggest command-and-control—hunt with DNS/proxy telemetry.",
    "arp-spoofing": "On-path attacks on flat LANs need segmentation, DHCP snooping, or 802.1X.",
    "dns-tunneling": "Abnormal query volume/entropy can exfiltrate data inside DNS—inspect resolvers and firewalls.",
    "traffic-inspection": "TLS inspection and NetFlow help detect exfil and C2 inside encrypted traffic.",
    "patching": "Prioritize known-exploited vulns; emergency change beats waiting for quarterly cycles.",
    "outdated-software": "EOL software lacks patches—segment, compensate, or retire with documented risk.",
    "config-drift": "Baseline configuration and IaC prevent silent weakening of security controls.",
    "update-compliance": "Measure patch SLA adherence; exceptions need risk acceptance and expiry.",
    "unsupported-os": "Unsupported OS on critical networks requires segmentation and explicit risk acceptance.",
    "vulnerable-apps": "Fix flaws at the source; WAF and perimeter controls are compensating, not sufficient.",
    "insecure-coding": "Prevent injection and auth bypass with secure APIs, validation, and secret hygiene.",
    "exploits": "Act on CISA KEV and vendor advisories for actively exploited vulnerabilities immediately.",
    "sast": "Shift-left scanning blocks secrets and critical flaws before production lineage.",
    "fraud-indicators": "Pattern analytics and verification stop gift-card, invoice, and vendor fraud schemes.",
    "accounting-integrity": "Segregation of duties and documented journal entries deter financial manipulation.",
    "workflow-protection": "Dual approval on banking and master-data changes blocks process abuse.",
    "invoice-manipulation": "Look-alike domains and changed remittance details need vendor verification.",
    "unauthorized-access": "Tailgating and propped doors defeat physical controls—train and monitor.",
    "device-theft": "Encryption and remote wipe reduce impact of lost laptops and mobile devices.",
    "badge-access": "Badge systems need provisioning tied to HR and anti-passback where appropriate.",
    "cctv": "Retention, placement, and privacy policies balance deterrence with legal requirements.",
    "hipaa": "PHI minimum necessary, BAAs, and breach notification are foundational HIPAA obligations.",
    "policy-adherence": "Policies must be measurable, enforced technically where possible, and audited.",
    "audit-readiness": "Evidence collection and control testing should be continuous, not cram-before-audit.",
    "documentation": "Runbooks, data flows, and asset inventories enable faster incident response.",
    "risk-management": "Risk registers and third-party scores must drive remediation and contract decisions.",
}
