#!/usr/bin/env python3
"""One-shot builder: writes comptia_fact_banks.py and comptia_acronyms.py."""
from __future__ import annotations

from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent / "question_bank"

# ---------------------------------------------------------------------------
# Helpers for fact tuples
# ---------------------------------------------------------------------------

def mcq(stem, correct, wrong, expl, alt=None):
    return (stem, correct, wrong, expl, alt)

def multi(stem, opts, correct, expl):
    return (stem, opts, correct, expl, None, None)

# ---------------------------------------------------------------------------
# A+ 220-1101 (Core 1 domains)
# ---------------------------------------------------------------------------

A_PLUS = {
    "mobile-devices": [
        mcq("Which connector is most common on modern Android smartphones for charging and data?",
            "USB-C", ("Micro-USB", "Mini-USB", "FireWire 400"),
            "USB-C is the standard reversible connector on current mobile devices.",
            "A technician must replace a damaged charging port on a flagship phone. Which port type is most likely required?"),
        mcq("Which mobile feature uses short-range NFC for contactless payments?",
            "Tap to pay (NFC)", ("GPS triangulation", "802.11ac only", "LiDAR mapping"),
            "NFC enables proximity-based transactions on mobile wallets."),
        mcq("Which iOS setting remotely locks and displays a message on a lost device?",
            "Lost Mode in Find My", ("AirDrop", "Handoff", "Screen Time"),
            "Lost Mode locks the device and can show owner contact info via iCloud.",
            "An iPhone is missing. Which feature lets IT lock it and show a recovery phone number?"),
        mcq("Which Android permission category controls access to the device camera?",
            "Camera", ("Storage manager", "NFC", "Developer options"),
            "Camera permission gates photo/video capture apps."),
        mcq("Which laptop feature converts a 2-in-1 into tablet mode via a rotating hinge?",
            "Convertible (360-degree hinge)", ("Docking station", "KVM switch", "RAID 0"),
            "Convertibles use rotating or detachable hinges for tablet use."),
        mcq("Which cellular generation introduced LTE-Advanced with higher throughput?",
            "4G LTE", ("2G GSM", "3G EDGE", "1G analog"),
            "4G LTE brought broadband-class mobile data speeds.",
            "Users report slow mobile data on an older phone limited to EDGE. Which generation should they upgrade toward for LTE?"),
        mcq("Which mobile OS component sandboxed apps to limit cross-app data access?",
            "Application sandbox", ("Boot loader", "Kernel panic handler", "CMOS battery"),
            "Mobile OSes isolate apps in sandboxes for security."),
        mcq("Which accessory extends laptop ports when the mobile device has limited I/O?",
            "USB-C hub or docking station", ("Surge protector only", "PoE injector", "Crossover cable"),
            "Docks and hubs add HDMI, USB-A, Ethernet, and charging.",
            "A ultrabook has one USB-C port. Which accessory adds HDMI and wired Ethernet?"),
        mcq("Which screen technology offers deep blacks on many flagship phones?",
            "OLED", ("TN panel", "CRTs", "Plasma"),
            "OLED pixels emit their own light, enabling true blacks."),
        mcq("Which mobile troubleshooting step clears stuck network registration?",
            "Toggle airplane mode or reseat SIM", ("Flash BIOS", "Replace CMOS", "Run CHKDSK"),
            "Airplane mode resets the cellular radio registration.",
            "A phone shows 'No Service' after travel. What is the first mobile-specific step?"),
        mcq("Which biometric method maps facial geometry on supported devices?",
            "Facial recognition (Face ID class)", ("Magnetic stripe", "Smart card contact", "WEP key"),
            "Structured-light or IR facial mapping unlocks devices."),
        mcq("Which tablet input accessory is pressure-sensitive for drawing?",
            "Active stylus", ("Capacitive passive stick only", "Trackball", "Touchpad"),
            "Active styluses support pressure and palm rejection."),
        mcq("Which mobile deployment model installs a work profile separate from personal apps?",
            "Android Enterprise work profile", ("Dual BIOS", "RAID 1", "Hyper-V replica"),
            "Work profiles containerize corporate data on BYOD devices."),
        mcq("Which connector did Apple Lightning replace on older iPhones?",
            "30-pin dock connector", ("USB-B", "DisplayPort", "eSATA"),
            "Lightning superseded the wide 30-pin connector."),
        mcq("Which mobile battery best practice preserves longevity?",
            "Avoid prolonged 100% charge and extreme heat", ("Always drain to 0%", "Fast-charge continuously overnight in hot car", "Remove battery while plugged in"),
            "Heat and constant full charge accelerate lithium wear."),
        mcq("Which wireless standard is typical for tethering a phone to a laptop?",
            "Wi-Fi hotspot (802.11)", ("Zigbee only", "Bluetooth LE mesh only", "IrDA"),
            "Personal hotspots share cellular data over Wi-Fi."),
        multi("Which TWO are common mobile device display issues? (Select TWO.)",
              [("a", "Ghost touch"), ("b", "Dead pixels"), ("c", "RAID degradation"), ("d", "POST beep codes"), ("e", "Burn-in on OLED")],
              ["a", "b", "e"], "Touch, pixel defects, and OLED burn-in are mobile display concerns."),
    ],
    "networking": [
        mcq("Which TCP port does HTTPS use by default?",
            "443", ("80", "21", "23"),
            "HTTPS encrypts HTTP traffic on port 443.",
            "A firewall rule must allow secure web browsing. Which port should be opened?"),
        mcq("Which OSI layer handles logical addressing with IP?",
            "Layer 3 (Network)", ("Layer 1", "Layer 2", "Layer 7 only"),
            "Layer 3 routes packets using IP addresses."),
        mcq("Which cable category supports 1 Gbps to 100 meters on copper?",
            "Cat 5e or higher", ("Cat 3", "Coax RG-59 only", "Twinax"),
            "Cat 5e/6/6a meet Gigabit Ethernet specs."),
        mcq("Which device separates collision domains on each port?",
            "Switch", ("Hub", "Repeater", "Patch panel only"),
            "Switches forward frames per MAC address, isolating collisions."),
        mcq("Which protocol dynamically assigns IPv4 addresses?",
            "DHCP", ("DNS", "FTP", "SNMP"),
            "DHCP leases IP, mask, gateway, and DNS to clients."),
        mcq("Which wireless band offers more channels but shorter range than 2.4 GHz?",
            "5 GHz", ("900 MHz ISM only", "AM broadcast", "Sub-1 GHz LoRa only"),
            "5 GHz has more non-overlapping channels at reduced range."),
        mcq("Which DNS record maps a hostname to an IPv4 address?",
            "A record", ("MX", "SRV", "CNAME only"),
            "A records resolve names to IPv4 addresses."),
        mcq("Which tool verifies Layer 1/Layer 2 link on an RJ-45 drop?",
            "Cable tester or certifier", ("Multimeter only for CPU", "Torque wrench", "Tone generator alone without probe"),
            "Cable testers check continuity, pairs, and often wire map."),
        mcq("Which IPv4 classless mask equals a /24 network?",
            "255.255.255.0", ("255.0.0.0", "255.255.254.0", "255.255.255.252"),
            "/24 leaves 8 host bits: 255.255.255.0."),
        mcq("Which protocol synchronizes time across networked devices?",
            "NTP", ("Telnet", "POP3", "IMAP"),
            "NTP keeps clocks aligned for logs and certificates."),
        mcq("Which connector is standard on twisted-pair Ethernet?",
            "RJ-45", ("RJ-11", "BNC", "F-type"),
            "RJ-45 is the 8P8C connector for Ethernet."),
        mcq("Which address range is private RFC 1918 space?",
            "10.0.0.0/8", ("8.8.8.0/24 public", "169.254.0.0 APIPA example still link-local", "1.1.1.0/24"),
            "10/8, 172.16/12, and 192.168/16 are private."),
        mcq("Which wireless security mode provides per-user authentication on enterprise WLANs?",
            "WPA2/WPA3-Enterprise (802.1X)", ("WEP", "Open SSID", "SSID hiding alone"),
            "802.1X with RADIUS authenticates users individually."),
        mcq("Which command on Windows displays the IP configuration?",
            "ipconfig", ("ifconfig on Linux primarily", "format", "diskpart"),
            "ipconfig /all shows IPv4, DNS, and MAC on Windows."),
        mcq("Which fiber connector is common in data centers with a latch?",
            "LC", ("RJ-45", "DE-9", "Centronics 36"),
            "LC is widely used on SFP/SFP+ transceivers."),
        mcq("Which protocol resolves MAC addresses from known IPv4 addresses on a LAN?",
            "ARP", ("ICMP only", "SMTP", "LDAP"),
            "ARP maps IP to MAC on the local segment."),
        multi("Which TWO are valid IPv6 address types? (Select TWO.)",
              [("a", "Global unicast"), ("b", "Link-local (fe80::/10)"), ("c", "Broadcast (like IPv4)"), ("d", "WEP key"), ("e", "Loopback (::1)")],
              ["a", "b", "e"], "IPv6 uses unicast, link-local, and ::1 loopback; no broadcast."),
    ],
    "hardware": [
        mcq("Which component temporarily holds running programs and active data?",
            "RAM", ("HDD", "ROM BIOS chip only", "PSU"),
            "RAM is volatile working memory for the CPU."),
        mcq("Which CPU socket type must match the motherboard?",
            "Physical socket standard (e.g., LGA1700, AM5)", ("DDR5 speed only", "Case form factor", "Monitor refresh rate"),
            "CPU package must fit the board socket/chipset."),
        mcq("Which storage interface offers NVMe speeds over PCIe?",
            "M.2 NVMe", ("PATA", "Floppy", "IDE ribbon"),
            "NVMe SSDs on M.2 use PCIe lanes."),
        mcq("Which printer technology uses toner and a heated fuser?",
            "Laser", ("Inkjet", "Dot matrix", "Thermal receipt only"),
            "Laser printers fuse toner to paper with heat."),
        mcq("Which power supply rating indicates higher efficiency at typical loads?",
            "80 PLUS Gold or better", ("ATX size only", "Molex count", "RGB lighting"),
            "80 PLUS tiers reflect efficiency at 20/50/100% load."),
        mcq("Which RAID level mirrors data across two disks?",
            "RAID 1", ("RAID 0", "RAID 5 alone without parity description", "JBOD striping only"),
            "RAID 1 writes identical copies for redundancy."),
        mcq("Which tool measures voltage, continuity, and resistance?",
            "Multimeter", ("Torx driver", "Cable crimper only", "Anti-static bag"),
            "Multimeters diagnose power and circuit issues."),
        mcq("Which BIOS/UEFI setting boots from USB for OS installation?",
            "Boot order / boot override", ("Spread spectrum always off", "CPU fan curve RGB", "Secure Boot disable only"),
            "Boot order or one-time boot menu selects install media."),
        mcq("Which GPU resource is most critical for 3D gaming performance?",
            "VRAM and GPU core", ("Keyboard polling rate", "Case fan CFM only", "Sound card SNR"),
            "Graphics workloads depend on GPU and video memory."),
        mcq("Which laptop component replacement requires matching wattage and connector?",
            "AC adapter", ("LCD hinge grease", "Touchpad firmware", "Wi-Fi SSID"),
            "Adapters must meet voltage, amperage, and tip specs."),
        mcq("Which ESD practice protects components during repair?",
            "Wrist strap bonded to ground", ("Work on carpet in dry winter", "Touch PSU while plugged in", "Wrap board in plastic"),
            "Grounded straps dissipate static safely."),
        mcq("Which connector powers most discrete GPUs directly from the PSU?",
            "6/8-pin PCIe power", ("SATA data", "USB-A", "PS/2"),
            "High-watt GPUs need dedicated PCIe power connectors."),
        mcq("Which memory type is error-correcting and common on servers?",
            "ECC RAM", ("Non-ECC SO-DIMM only in all cases", "VRAM", "Cache L1 only"),
            "ECC detects/corrects single-bit memory errors."),
        mcq("Which symptom suggests failing capacitors on a motherboard?",
            "Bulging or leaking capacitors", ("Higher FPS", "Lower latency ping", "Brighter display"),
            "Bad caps cause instability, boot failures, or shutdowns."),
        mcq("Which printer maintenance fixes streaks on laser output?",
            "Replace drum or toner cartridge", ("Flash BIOS", "Defrag HDD", "Renew DHCP"),
            "Worn drums or low toner cause repeating streaks."),
        mcq("Which form factor is smallest for mainstream desktop boards?",
            "Mini-ITX", ("E-ATX", "ATX full tower only", "SSI CEB"),
            "Mini-ITX is the compact consumer standard."),
        mcq("Which primary PC cooling assembly transfers heat from the CPU to air?",
            "CPU heatsink and fan", ("Only thermal paste without a heatsink", "LCD backlight inverter", "Inkjet fuser unit"),
            "Heatsinks spread heat; fans move air across fins."),
        mcq("Which display interface commonly supports daisy-chaining multiple monitors?",
            "DisplayPort", ("VGA analog only", "PS/2 keyboard", "RJ-11 telephone"),
            "DisplayPort MST can chain compatible monitors."),
        mcq("Which motherboard component manages communication between CPU, RAM, and PCIe devices?",
            "Chipset (PCH)", ("CRT electron gun", "Toner hopper", "Ribbon cable only"),
            "The chipset routes I/O and peripheral traffic."),
        mcq("Which storage technology has no spinning platters?",
            "Solid-state drive (SSD)", ("Traditional HDD", "Floppy disk", "Magnetic tape cartridge"),
            "SSDs use flash memory with no mechanical spindles."),
        multi("Which TWO are hot-swappable in many server designs? (Select TWO.)",
              [("a", "SATA/SAS drive in hot-swap bay"), ("b", "CPU without shutdown"), ("c", "Fans in redundant trays"), ("d", "System RAM while powered"), ("e", "PSU in redundant module")],
              ["a", "c", "e"], "Drives, fans, and redundant PSUs often support hot swap."),
    ],
    "virtualization-cloud": [
        mcq("Which hypervisor runs directly on hardware without a host OS?",
            "Type 1 (bare-metal)", ("Type 2 hosted only", "Container runtime only", "BIOS utility"),
            "Type 1 hypervisors (ESXi, Hyper-V host) sit on bare metal."),
        mcq("Which cloud model provides ready-to-use applications over the internet?",
            "SaaS", ("IaaS only", "PaaS only", "Private cloud on-prem only"),
            "SaaS delivers apps like email or CRM as a service."),
        mcq("Which virtual network device connects VMs to the physical LAN?",
            "Virtual switch (vSwitch)", ("Virtual PSU", "Virtual GPU driver only", "Virtual CMOS"),
            "vSwitches bridge VM NICs to physical uplinks."),
        mcq("Which resource can be oversubscribed carefully in VDI pools?",
            "vCPU and RAM (with monitoring)", ("Physical monitor count", "Keyboard layout", "Printer paper"),
            "VDI hosts share CPU/RAM across many sessions with limits."),
        mcq("Which Azure service category is IaaS?",
            "Virtual Machines", ("Microsoft 365 apps", "Azure DevOps boards SaaS", "DNS registrar only"),
            "VMs are infrastructure you manage at the OS layer."),
        mcq("Which feature snapshots a VM state for rollback?",
            "Checkpoint / snapshot", ("Defragment VHD only", "RAID 0", "Overclock vCPU"),
            "Snapshots capture disk and memory state points."),
        mcq("Which container shares the host kernel unlike full VMs?",
            "Docker-style container", ("Full hardware VM always isolated kernel", "Physical server", "Tape backup"),
            "Containers share the OS kernel with isolation namespaces."),
        mcq("Which cloud deployment mixes on-premises and public cloud?",
            "Hybrid cloud", ("Air gap only", "Sneaker net", "Standalone kiosk"),
            "Hybrid connects private datacenter workloads to public cloud."),
        mcq("Which AWS offering is object storage?",
            "Amazon S3", ("Amazon EC2 compute", "Amazon RDS DB engine", "Amazon VPC router"),
            "S3 stores objects in buckets with high durability."),
        mcq("Which virtual disk format is common on VMware?",
            "VMDK", ("DOCX", "MP4", "ISO only for install media"),
            "VMDK is VMware's virtual disk format."),
        mcq("Which practice right-sizes cloud VMs to control cost?",
            "Monitor utilization and resize instances", ("Always use largest SKU", "Disable billing alerts", "Never use autoscaling"),
            "Rightsizing matches instance size to actual load."),
        mcq("Which Google workspace tier is SaaS productivity?",
            "Google Workspace", ("Compute Engine IaaS", "Cloud Spanner DB", "Cloud VPN"),
            "Workspace provides Gmail, Drive, and Docs as SaaS."),
        mcq("Which hypervisor feature deduplicates identical memory pages across VMs?",
            "Memory ballooning / transparent page sharing class features", ("RGB fan control", "Overvoltage CPU", "Disable NIC"),
            "Hypervisors optimize RAM via sharing and balloon drivers."),
        mcq("Which remote access protocol commonly accesses Windows VMs in cloud?",
            "RDP", ("Telnet", "FTP", "SNMP"),
            "RDP provides GUI remote desktop to Windows hosts."),
        mcq("Which license concern applies when migrating Windows desktops to VDI?",
            "Windows licensing for virtual desktops (VDI/SPLA rules)", ("Monitor refresh licensing", "Keyboard layout patent", "HDMI copyright"),
            "VDI requires appropriate Microsoft licensing."),
        mcq("Which metric triggers auto-scaling of web servers in cloud?",
            "CPU or request latency thresholds", ("Desktop wallpaper color", "USB device count", "Fan RPM only"),
            "Autoscale adds/removes instances on load metrics."),
        multi("Which TWO are benefits of virtualization? (Select TWO.)",
              [("a", "Hardware consolidation"), ("b", "Mandatory single OS globally"), ("c", "Fast provisioning from templates"), ("d", "Eliminates all patching"), ("e", "Isolated test labs")],
              ["a", "c", "e"], "VMs consolidate hardware, clone quickly, and isolate environments."),
    ],
    "troubleshooting": [
        mcq("A PC powers on but shows no video. Which step comes first?",
            "Verify monitor input and cable seating", ("Replace CPU immediately", "Flash BIOS first", "Replace PSU without checks"),
            "Display path checks are quick and non-destructive."),
        mcq("Intermittent Wi-Fi drops on one laptop only. Best next step?",
            "Update Wi-Fi driver and check power management settings", ("Replace access point first", "Change ISP", "Replace all cables in building"),
            "Client-specific issues often involve drivers or power save."),
        mcq("A workstation cannot reach internal sites by name but can by IP. Likely cause?",
            "DNS failure or misconfiguration", ("Bad GPU", "Low toner", "RAID 0 failure"),
            "Name resolution failures point to DNS."),
        mcq("Blue screen after new RAM install. First action?",
            "Reseat modules and verify compatibility/slots", ("Install newest game", "Enable RAID 5", "Disable NIC"),
            "Improper seating or incompatible RAM causes crashes."),
        mcq("Printer queue stuck with jobs. Quick fix on Windows?",
            "Restart print spooler service", ("Replace fuser", "Flash printer BIOS always first", "Change DNS MX"),
            "Spooler restart clears stuck print jobs."),
        mcq("No POST beeps and no fans spin. Suspect?",
            "PSU failure or front panel power connection", ("Monitor OSD", "Driver update", "User GPO"),
            "No power delivery suggests PSU or power button wiring."),
        mcq("Slow boot after many startup apps. Remediation?",
            "Disable unnecessary startup programs", ("Add second GPU", "Increase wallpaper resolution", "Disable DHCP"),
            "Startup bloat delays logon and boot time."),
        mcq("Laptop overheats and throttles under load. Best maintenance?",
            "Clean vents and replace dried thermal paste if needed", ("Block vents for quiet", "Disable fans in BIOS", "Remove heat sink"),
            "Dust and paste degradation cause thermal throttling."),
        mcq("Network link light off on one desk. First hardware check?",
            "Test with known-good cable and switch port", ("Replace server CPU", "Reinstall OS", "Change domain password"),
            "Swap testing isolates cable, NIC, or port faults."),
        mcq("USB device not recognized on one port. Try?",
            "Different port and Device Manager check", ("Replace monitor", "Flash BIOS before any port test", "Format C:"),
            "Port, cable, or driver issues are common USB faults."),
        mcq("Clicking hard drive and slow access. Likely issue?",
            "Imminent drive failure — back up and replace", ("GPU overheating", "Low ink", "Stale DNS cache only"),
            "Mechanical clicking indicates failing HDD."),
        mcq("Mobile device rapid battery drain after update. Step?",
            "Check battery usage report and reset network settings if radio stuck", ("Replace screen", "Flash desktop BIOS", "Change RAID level"),
            "Updates can increase radio usage; usage stats identify culprits."),
        mcq("Cannot join domain — time skew error. Fix?",
            "Sync system time with domain controller/NTP", ("Replace keyboard", "Disable firewall entirely", "Add RAM"),
            "Kerberos fails when client clock skew exceeds policy."),
        mcq("Projector shows no signal from laptop. Check?",
            "Correct input source and duplicate/extend display mode", ("Replace projector lamp first always", "Update printer driver", "Run disk defrag"),
            "Input selection and display mirroring are common misses."),
        mcq("Random shutdowns under gaming load only. Suspect?",
            "PSU insufficient wattage or overheating GPU/CPU", ("DNS", "SMTP", "Low toner"),
            "Peak power or thermal limits cause load-specific shutdowns."),
        mcq("Workstation gets APIPA 169.254.x.x address. Cause?",
            "DHCP unreachable or failed lease", ("Correct static DNS", "Valid gateway", "Working DHCP server"),
            "APIPA indicates no DHCP offer received."),
        mcq("POST beep codes indicate RAM not detected. What should you try first?",
            "Power off, reseat RAM, and test one module at a time", ("Replace the GPU first", "Disable Secure Boot only", "Format the boot drive"),
            "RAM detection failures are often seating, slot, or module faults."),
        mcq("After a patch panel change, an entire floor loses wired network. Best focus?",
            "Verify cable pairs, switch port VLANs, and link lights", ("Reinstall every PC OS", "Replace all monitors", "Change Wi-Fi passphrase only"),
            "Physical layer and switch port mapping errors affect many hosts at once."),
        mcq("An inkjet printer shows color banding and streaks. First maintenance?",
            "Run print-head cleaning and alignment", ("Replace the laser fuser", "Flash the motherboard BIOS", "Defragment the HDD"),
            "Clogged nozzles and misalignment cause banding on inkjets."),
        mcq("A replaced laptop touchscreen is inaccurate at the edges. Next step?",
            "Calibrate the touch panel in OS settings", ("Replace the PSU", "Disable DHCP", "Enable RAID 0"),
            "Calibration maps touch coordinates to the display."),
        mcq("Windows reports MEMORY_MANAGEMENT BSOD after a driver update. What helps isolate it?",
            "Roll back the driver and test RAM with a memory diagnostic", ("Increase screen brightness", "Disable the print spooler only", "Change DNS to public only"),
            "Bad drivers and faulty RAM both trigger memory management crashes."),
        mcq("An external monitor flickers only when using a USB-C dock. Likely fix?",
            "Update dock firmware and GPU/display drivers", ("Replace keyboard caps", "Lower toner density", "Disable NTP"),
            "Docks and GPU drivers must support the display mode and bandwidth."),
        mcq("A desktop wakes from sleep immediately at night without user input. Check?",
            "Review wake timers, scheduled tasks, and peripheral wake settings", ("Replace CPU thermal paste first", "Flash printer firmware", "Change cable category to Cat3"),
            "Scheduled tasks, mice, keyboards, and network adapters can wake the system."),
        multi("Which TWO steps are safe general troubleshooting practices? (Select TWO.)",
              [("a", "Document symptoms and changes"), ("b", "Change many variables at once"), ("c", "Establish a theory and test"), ("d", "Skip backups before disk work"), ("e", "Verify fixes with users")],
              ["a", "c", "e"], "Structured troubleshooting changes one thing at a time and verifies outcomes."),
    ],
}

# Due to file size, remaining exams are appended via the builder's data module pattern.
# Import extended banks from inline definitions below.

NETWORK_PLUS = {
    "concepts": [
        mcq("Which model has seven layers including Application and Transport?",
            "OSI model", ("TCP/IP 4-layer only name", "DoD 2-layer", "ISO 9001"),
            "The OSI reference model defines seven layers.",
            "On the Network+ exam, which reference model includes Session, Presentation, and Application layers?"),
        mcq("Which protocol provides connectionless delivery at Layer 4?",
            "UDP", ("TCP", "SCTP always ordered", "FTP"),
            "UDP has no handshake or guaranteed delivery."),
        mcq("Which IPv6 address is the loopback address?",
            "::1/128", ("127.0.0.1", "0.0.0.0", "255.255.255.255"),
            "IPv6 loopback is ::1."),
        mcq("Which subnet mask creates four equal subnets from a /24?",
            "/26", ("/25", "/30", "/32"),
            "/26 yields four subnets with 62 usable hosts each in a classful-style split."),
        mcq("Which port does DNS use for queries primarily?",
            "53", ("443", "22", "3389"),
            "DNS typically uses UDP/TCP port 53."),
        mcq("Which wireless standard introduced WPA3?",
            "802.11ax era security updates include WPA3", ("802.11b WEP only", "802.3 Ethernet", "Bluetooth Classic"),
            "WPA3 strengthens Wi-Fi authentication and encryption."),
        mcq("Which device operates at Layer 3 and routes between networks?",
            "Router", ("Unmanaged switch", "Hub", "Patch panel"),
            "Routers forward based on IP routing tables."),
        mcq("Which cable type is immune to EMI for long campus runs?",
            "Single-mode fiber", ("Cat 3 UTP", "Coax RG-59 only", "Flat telephone wire"),
            "Fiber uses light, avoiding electrical interference."),
        mcq("Which QoS mechanism marks packets for priority treatment?",
            "DSCP", ("ARP", "SMTP", "POP3"),
            "Differentiated Services Code Point marks traffic classes."),
        mcq("Which topology has a single cable backbone with terminators?",
            "Bus (legacy Ethernet coax)", ("Full mesh modern default", "Star over switch is not bus", "Ring Token Ring class"),
            "Classic bus topology uses coax with end terminators."),
        mcq("Which IPv4 address is limited broadcast?",
            "255.255.255.255", ("127.0.0.1", "0.0.0.0", "224.0.0.1"),
            "255.255.255.255 is local broadcast."),
        mcq("Which protocol maps port numbers to services?",
            "Well-known ports in TCP/UDP (e.g., 80 HTTP)", ("DNS only MX", "ICMP type 0 only", "LDAP schema"),
            "IANA assigns well-known ports for services."),
        mcq("Which encapsulation order is correct for TCP/IP stack?",
            "Data, Segment, Packet, Frame, Bits", ("Bits first at application", "Frame before packet always wrong", "Segment at layer 2"),
            "PDU names change per layer down the stack."),
        mcq("Which IPv6 feature eliminates NAT need in pure deployments?",
            "Large address space", ("WEP", "SSID hiding", "MAC filtering only"),
            "128-bit addresses reduce NAT dependency."),
        mcq("Which network type spans a city between campuses?",
            "MAN", ("PAN", "LAN only single floor", "SAN storage network not geographic MAN"),
            "Metropolitan Area Networks cover cities."),
        mcq("Which ICMP message supports ping?",
            "Echo Request/Echo Reply", ("SYN-ACK", "DHCP OFFER", "ARP Reply"),
            "Ping uses ICMP echo messages."),
        mcq("(Network+ pool) Supplemental concepts item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(Network+ pool) Supplemental concepts item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
                multi("Which TWO are private IPv4 ranges? (Select TWO.)",
              [("a", "192.168.1.0/24"), ("b", "172.16.0.0/12"), ("c", "8.8.8.0/24"), ("d", "1.1.1.0/24"), ("e", "11.0.0.0/8 public")],
              ["a", "b"], "192.168/16 and 172.16/12 are RFC 1918 private space."),
    ],
    "implementation": [
        mcq("Which routing protocol is distance-vector and uses hop count?",
            "RIP", ("OSPF link-state", "BGP path vector external", "IS-IS only datacenter"),
            "RIP selects paths by hop count with limits."),
        mcq("Which VLAN ID is reserved on Cisco-style switches?",
            "4095 or implementation-specific reserved; VLAN 1 default", ("VLAN 0 data", "VLAN 9999 always routing", "VLAN -1"),
            "VLAN 1 is default; vendors reserve certain IDs."),
        mcq("Which PoE standard supports up to 30W per port (802.3at)?",
            "PoE+", ("PoE 802.3af 15.4W class", "Passive 24V always", "USB-A power"),
            "802.3at (PoE+) delivers higher wattage."),
        mcq("Which DNS server type holds authoritative zone records?",
            "Primary authoritative server", ("Root hint only client", "DHCP server", "NTP stratum 0"),
            "Authoritative servers store zone data."),
        mcq("Which WAN technology uses virtual circuits over packet switching?",
            "Frame Relay (legacy) / MPLS VPN concept", ("Dial-up modem only", "Parallel printer cable", "HDMI"),
            "Many WANs use label-switched or VC technologies."),
        mcq("Which firewall rule direction blocks inbound by default in hardened design?",
            "Implicit deny inbound after explicit permits", ("Allow all then log", "Deny outbound only", "Permit any any first"),
            "Default deny inbound is a security baseline."),
        mcq("Which 802.11 mode bonds channels for higher throughput?",
            "Channel bonding / 40/80/160 MHz widths", ("WEP shared key", "Half duplex fiber", "CSMA/CD on switch"),
            "Wider channels increase Wi-Fi data rates."),
        mcq("Which device terminates many SSL VPN sessions?",
            "VPN concentrator or firewall with VPN", ("Unmanaged hub", "Analog modem bank only", "KVM"),
            "VPN gateways handle encrypted remote access."),
        mcq("Which IPv6 configuration method uses routers to advertise prefixes?",
            "SLAAC with RA", ("ARP only", "WINS", "NetBIOS"),
            "Router Advertisements enable SLAAC addressing."),
        mcq("Which cable tester result indicates split pair wiring fault?",
            "Wire map shows pins crossed between pairs", ("Link light green only", "Ping success", "DNS OK"),
            "Split pairs cause crosstalk and errors."),
        mcq("Which SD-WAN benefit optimizes multi-link use?",
            "Dynamic path selection by application/policy", ("Static route only one link", "Disable encryption", "Remove QoS"),
            "SD-WAN steers traffic across MPLS/broadband/LTE."),
        mcq("Which switch feature prevents loops while allowing redundancy?",
            "Spanning Tree Protocol (STP/RSTP)", ("Port mirroring", "PoE", "VLAN tagging only"),
            "STP blocks redundant paths to avoid loops."),
        mcq("Which authentication protocol is used with WPA2-Enterprise?",
            "802.1X with EAP", ("WEP key index", "MAC clone only", "SSID broadcast off"),
            "802.1X controls port access before Wi-Fi data."),
        mcq("Which IPv4 CIDR block has 14 usable host addresses?",
            "/28", ("/24", "/16", "/8"),
            "/28 leaves 4 host bits = 16 addresses, 14 usable."),
        mcq("Which load balancer mode distributes based on source IP hash?",
            "Source IP affinity / persistence", ("Round robin DNS only always layer 7", "Broadcast storm", "ARP proxy only"),
            "Persistence sticks sessions to the same backend."),
        mcq("Which transceiver form factor is hot-swappable on switches?",
            "SFP/SFP+", ("RJ-11", "DE-9 serial", "Molex"),
            "SFP modules plug into switch slots for fiber/copper."),
        multi("Which TWO are required for a functioning DHCP IPv4 lease? (Select TWO.)",
              [("a", "Available addresses in scope"), ("b", "Default gateway option often provided"), ("c", "WEP key index"), ("d", "MX record"), ("e", "Subnet mask")],
              ["a", "b", "e"], "DHCP scopes need addresses, mask, and usually gateway/DNS options."),
    ],
    "operations": [
        mcq("Which documentation shows device interconnections and ports?",
            "Network diagram / ladder diagram", ("Privacy policy", "Employee handbook", "Toner inventory"),
            "Diagrams map topology for operations."),
        mcq("Which SNMP version adds encryption and authentication?",
            "SNMPv3", ("SNMPv1 community public only", "Telnet", "FTP"),
            "SNMPv3 supports authPriv security models."),
        mcq("Which backup type copies only changed blocks since last full?",
            "Incremental", ("Full every time only", "Mirror snap always full copy", "Archive tape label"),
            "Incrementals store changes since last backup of any type."),
        mcq("Which KPI measures time between failures?",
            "MTBF", ("MTTR repair time", "RPO", "RTO"),
            "Mean Time Between Failures indicates reliability."),
        mcq("Which change management step validates rollback?",
            "Backout plan documented before change", ("Skip CAB", "Deploy Friday 5 PM always", "No testing"),
            "Rollback plans reduce outage risk."),
        mcq("Which log source shows authentication failures on Linux?",
            "/var/log/auth.log or secure", ("access.log web only", "spooler", "CUPS error"),
            "Auth logs capture SSH and sudo events."),
        mcq("Which monitoring alert indicates interface saturation?",
            "Sustained high utilization/errors on SNMP ifInOctets", ("User birthday", "Printer low ink once", "Desktop wallpaper change"),
            "Interface counters reveal congestion and errors."),
        mcq("Which wireless survey tool heatmaps signal strength?",
            "Site survey software with AP on a map", ("Cable toner", "Multimeter", "Torque driver"),
            "Surveys visualize RSSI and interference."),
        mcq("Which SLA metric defines allowed yearly downtime?",
            "Availability percentage (e.g., 99.9%)", ("MTBF only", "Password length", "SSID name"),
            "Availability SLAs express uptime targets."),
        mcq("Which configuration management stores device configs centrally?",
            "Git-backed repo or NCM tool", ("Sticky notes", "Local only on each device unversioned", "Spreadsheet on USB"),
            "Versioned configs enable audit and rollback."),
        mcq("Which patch window practice reduces user impact?",
            "Maintenance window with notifications", ("Silent prod patch noon", "Never patch", "Disable AV first always"),
            "Scheduled windows coordinate downtime."),
        mcq("Which DNS monitoring detects hijacking or stale records?",
            "Synthetic queries and DNSSEC validation where used", ("Ping only one host", "Ignore TTL", "Disable logging"),
            "Proactive DNS checks catch poisoned or stale answers."),
        mcq("Which cable management aids airflow in racks?",
            "Vertical/horizontal managers and dress paths", ("Cable spaghetti blocking vents", "Zip ties over-tightened crushing pairs", "Loose coils on floor"),
            "Proper dressing improves cooling and troubleshooting."),
        mcq("Which wireless controller function pushes SSID configs to APs?",
            "Centralized WLAN management", ("Per-AP manual only always", "DHCP server role only", "SMTP relay"),
            "Controllers provision lightweight APs at scale."),
        mcq("Which incident severity involves total site outage?",
            "Sev 1 / P1 critical", ("Low cosmetic", "Enhancement request", "Training ticket"),
            "P1 incidents are business-critical outages."),
        mcq("Which tool captures packets for protocol analysis?",
            "Wireshark/tcpdump", ("Ping only", "Tracert only", "Speedtest alone"),
            "Packet captures decode conversations on the wire."),
        multi("Which TWO are network hardening steps? (Select TWO.)",
              [("a", "Disable unused ports"), ("b", "Use default SNMP public"), ("c", "Implement ACLs"), ("d", "Publish admin passwords"), ("e", "Enable secure management (SSH)")],
              ["a", "c", "e"], "Disable unused services, ACLs, and secure management reduce attack surface."),
    ],
    "security": [
        mcq("Which attack floods a target with traffic to deny service?",
            "DoS/DDoS", ("Phishing email only", "Shoulder surfing", "Dumpster diving"),
            "Volume-based attacks overwhelm resources."),
        mcq("Which port security feature limits MAC addresses on a switch port?",
            "Port security sticky/learned limits", ("VLAN hopping always desired", "STP root guard off", "Open DHCP"),
            "Port security restricts learned MAC count."),
        mcq("Which VPN protocol runs on SSL/TLS port 443 often?",
            "OpenVPN or SSL VPN variants", ("PPTP only", "Telnet VPN", "FTP"),
            "SSL VPNs traverse firewalls using HTTPS port."),
        mcq("Which wireless attack uses rogue AP with same SSID?",
            "Evil twin", ("Bluejacking only", "Tailgating physical", "SQL injection"),
            "Evil twins trick clients into malicious APs."),
        mcq("Which NAC solution checks endpoint health before network access?",
            "802.1X with posture assessment", ("WEP rotation", "MAC spoof allowed", "Open guest always"),
            "NAC validates compliance before admission."),
        mcq("Which encryption protects Wi-Fi payloads in WPA2-PSK?",
            "AES-CCMP", ("WEP RC4", "Plaintext", "ROT13"),
            "WPA2 personal uses AES with CCMP."),
        mcq("Which firewall type inspects application layer data?",
            "Next-generation firewall (NGFW)", ("Layer 1 hub", "Passive patch panel", "Repeater"),
            "NGFWs include app-aware policies."),
        mcq("Which certificate problem breaks HTTPS trust?",
            "Expired or untrusted CA signature", ("Valid SAN match", "Correct chain", "Trusted root"),
            "Browsers warn on bad cert chains or expiry."),
        mcq("Which segmentation limits east-west malware spread?",
            "Micro-segmentation / VLAN ACLs", ("Flat network one VLAN", "Shared admin password", "Disable logging"),
            "Segmentation contains lateral movement."),
        mcq("Which remote access method avoids exposing RDP directly?",
            "VPN then RDP over private network", ("RDP port-forwarded open to internet", "Telnet admin", "FTP admin"),
            "VPN reduces exposure of management ports."),
        mcq("Which attack captures DHCP offers to become default gateway?",
            "DHCP starvation/spoofing (rogue server)", ("ARP only unrelated", "DNSSEC", "NTP leap"),
            "Rogue DHCP can redirect traffic via bad gateway."),
        mcq("Which HIDS tool monitors host logs and integrity?",
            "OSSEC/Wazuh-class HIDS", ("Unmanaged hub", "Cable tester", "Label maker"),
            "HIDS agents detect file and log anomalies."),
        mcq("Which wireless mitigation reduces rogue AP risk?",
            "WIPS scanning and ACL on wired uplinks", ("Hide SSID only", "WEP", "Disable encryption for speed"),
            "Wireless IPS detects unauthorized APs."),
        mcq("Which authentication factor is a hardware token?",
            "Something you have", ("Something you are only", "Somewhere you are always", "Something you ignore"),
            "Tokens are possession factors."),
        mcq("Which protocol secures SNMP monitoring?",
            "SNMPv3 authPriv", ("SNMPv1 public/private defaults", "Telnet", "HTTP basic only"),
            "SNMPv3 encrypts and authenticates messages."),
        mcq("Which email security record helps prevent spoofing?",
            "SPF/DKIM/DMARC", ("MX only", "A record only", "CNAME loop"),
            "Email auth records reduce forged sender mail."),
        multi("Which TWO mitigate VLAN hopping? (Select TWO.)",
              [("a", "Disable DTP/auto-trunk on access ports"), ("b", "Enable native VLAN tagging best practices"), ("c", "Use default VLAN 1 for all user traffic"), ("d", "Publish SNMP community"), ("e", "Prune unused VLANs from trunks")],
              ["a", "e"], "Secure trunk/access port settings and VLAN pruning reduce hopping."),
    ],
    "troubleshooting": [
        mcq("High latency to a remote site over VPN. First check?",
            "Measure path with traceroute/MTR and check link utilization", ("Replace all PCs", "Change DNS MX", "Disable STP globally"),
            "Path and congestion analysis isolates WAN issues."),
        mcq("Users get wrong IP subnet after office move. Cause?",
            "Mis-scoped DHCP or relay pointing to old server", ("GPU driver", "Low ink", "Monitor refresh"),
            "DHCP scope/relay errors assign wrong networks."),
        mcq("Intermittent CRC errors on one switch port. Fix?",
            "Replace patch cable and inspect SFP/transceiver", ("Update desktop wallpaper", "Flash BIOS on laptops", "Change AD password policy"),
            "Bad cables or optics cause CRC/FCS errors."),
        mcq("Wi-Fi clients connect but captive portal never appears. Check?",
            "DNS and firewall rules for walled garden URLs", ("Printer queue", "RAID rebuild", "CPU paste"),
            "Portals require DNS/HTTP allow lists to redirect."),
        mcq("Single host cannot reach internet but peers can. Next?",
            "Compare gateway, DNS, and ACL on host vs working peer", ("Replace core router first", "Reinstall building OS", "Disable DHCP globally"),
            "Host-specific config or ACL differs from working stations."),
        mcq("Duplicate IP warnings on LAN. Resolution?",
            "Identify conflicting static/DHCP leases and reconcile", ("Add second default gateway randomly", "Disable ARP", "Enable WEP"),
            "Duplicate addresses break connectivity for both hosts."),
        mcq("Slow file share on gigabit link. Verify?",
            "Negotiated speed/duplex and cable category", ("Toner level", "Keyboard layout", "BIOS date"),
            "Half-duplex or 100 Mbps link reduces throughput."),
        mcq("BGP session down after firewall change. Likely?",
            "TCP 179 blocked between peers", ("DNS failure", "SMTP relay", "Printer spooler"),
            "BGP uses TCP port 179 between routers."),
        mcq("VoIP choppy on congested link. Mitigate?",
            "Implement QoS marking/queuing for voice VLAN", ("Disable VLANs", "Remove PoE", "Use hub"),
            "Priority queuing protects real-time traffic."),
        mcq("Remote office tunnel up but no routes to HQ subnets. Fix?",
            "Advertise/install correct phase 2 selectors/static routes", ("Change SSID", "Replace mouse", "Update GPU driver"),
            "Missing routes prevent cross-site reachability."),
        mcq("SSL cert warning on internal site only. Cause?",
            "Internal CA not trusted on client or cert name mismatch", ("External DNS root issue only always", "Low RAM", "Wrong keyboard"),
            "Trust store or SAN mismatch causes local HTTPS warnings."),
        mcq("Multicast video fails across subnets. Need?",
            "IGMP snooping and PIM routing configured", ("Disable STP", "Use WEP", "Flat single VLAN only always wrong for large net"),
            "Multicast routing controls group membership across VLANs."),
        mcq("Fiber link flaps every few minutes. Inspect?",
            "Dirty connectors, bend radius, and optical power levels", ("DNS TTL", "SMTP banner", "User GPO wallpaper"),
            "Physical layer issues cause intermittent fiber links."),
        mcq("After lightning, switch stack partial failure. Step?",
            "Check PoE budget, damaged ports, and redundant power", ("Format laptops", "Renew DHCP on clients only", "Disable UPS"),
            "Power surges damage ports/modules; verify hardware health."),
        mcq("Captive portal auth works on Android not iOS. Check?",
            "Private MAC/Wi-Fi privacy randomization breaking portal auth", ("RAID level", "Printer driver", "CPU socket"),
            "Random MAC features can break MAC-based portal policies."),
        mcq("Traceroute stops at firewall. Interpretation?",
            "ICMP/time-exceeded filtered — not always outage", ("Target definitely down always", "DNS broken always", "Cable bad always"),
            "Filters hide hops; verify with allowed probes/end-to-end tests."),
        mcq("(Network+ pool) Supplemental troubleshooting item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(Network+ pool) Supplemental troubleshooting item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        multi("Which TWO tools diagnose DNS issues? (Select TWO.)",
              [("a", "nslookup/dig"), ("b", "Cable toner only"), ("c", "Resolve with known server"), ("d", "Multimeter continuity on RJ-45 for app layer"), ("e", "Check forward/reverse zones")],
              ["a", "c", "e"], "Query tools and zone checks validate DNS resolution."),
    ],
}

# Continue with SECURITY_PLUS, CYSA, LINUX in part 2 - write via exec from file

FACT_BANKS = {
    "comptia-a-plus": A_PLUS,
    "comptia-network-plus": NETWORK_PLUS,
}

ACRONYMS = {
    "comptia-a-plus": [
        {"term": "BIOS", "expansion": "Basic Input/Output System", "hint": "Firmware that initializes hardware at boot", "category": "Hardware"},
        {"term": "UEFI", "expansion": "Unified Extensible Firmware Interface", "hint": "Modern firmware interface replacing legacy BIOS", "category": "Hardware"},
        {"term": "CPU", "expansion": "Central Processing Unit", "hint": "Primary processor executing instructions", "category": "Hardware"},
        {"term": "GPU", "expansion": "Graphics Processing Unit", "hint": "Accelerates rendering and parallel compute", "category": "Hardware"},
        {"term": "RAM", "expansion": "Random Access Memory", "hint": "Volatile memory for active workloads", "category": "Hardware"},
        {"term": "SSD", "expansion": "Solid State Drive", "hint": "Flash storage without moving parts", "category": "Storage"},
        {"term": "HDD", "expansion": "Hard Disk Drive", "hint": "Magnetic spinning-platter storage", "category": "Storage"},
        {"term": "NVMe", "expansion": "Non-Volatile Memory express", "hint": "PCIe protocol for fast SSDs", "category": "Storage"},
        {"term": "SATA", "expansion": "Serial Advanced Technology Attachment", "hint": "Common drive interface for HDD/SSD", "category": "Storage"},
        {"term": "RAID", "expansion": "Redundant Array of Independent Disks", "hint": "Combines disks for performance or redundancy", "category": "Storage"},
        {"term": "USB", "expansion": "Universal Serial Bus", "hint": "Standard peripheral interconnect", "category": "Mobile/IO"},
        {"term": "NFC", "expansion": "Near Field Communication", "hint": "Short-range contactless communication", "category": "Mobile"},
        {"term": "LCD", "expansion": "Liquid Crystal Display", "hint": "Flat-panel display technology", "category": "Mobile"},
        {"term": "OLED", "expansion": "Organic Light-Emitting Diode", "hint": "Self-emissive display with deep blacks", "category": "Mobile"},
        {"term": "Wi-Fi", "expansion": "Wireless Fidelity (IEEE 802.11)", "hint": "Wireless LAN brand/protocol family", "category": "Networking"},
        {"term": "TCP", "expansion": "Transmission Control Protocol", "hint": "Connection-oriented transport protocol", "category": "Networking"},
        {"term": "IP", "expansion": "Internet Protocol", "hint": "Layer 3 addressing and routing", "category": "Networking"},
        {"term": "DNS", "expansion": "Domain Name System", "hint": "Resolves names to IP addresses", "category": "Networking"},
        {"term": "DHCP", "expansion": "Dynamic Host Configuration Protocol", "hint": "Automates IP address assignment", "category": "Networking"},
        {"term": "HTTP", "expansion": "Hypertext Transfer Protocol", "hint": "Web traffic on port 80 by default", "category": "Networking"},
        {"term": "HTTPS", "expansion": "HTTP Secure", "hint": "HTTP over TLS, port 443", "category": "Networking"},
        {"term": "FTP", "expansion": "File Transfer Protocol", "hint": "Transfers files, often ports 20/21", "category": "Networking"},
        {"term": "SSH", "expansion": "Secure Shell", "hint": "Encrypted remote terminal/file access", "category": "Networking"},
        {"term": "RJ-45", "expansion": "Registered Jack 45", "hint": "8P8C connector for Ethernet", "category": "Cabling"},
        {"term": "PoE", "expansion": "Power over Ethernet", "hint": "Delivers power on Ethernet pairs", "category": "Networking"},
        {"term": "VPN", "expansion": "Virtual Private Network", "hint": "Encrypted tunnel over public networks", "category": "Networking"},
        {"term": "SSID", "expansion": "Service Set Identifier", "hint": "Wireless network name", "category": "Wireless"},
        {"term": "WPA2", "expansion": "Wi-Fi Protected Access 2", "hint": "Wi-Fi security using AES-CCMP", "category": "Wireless"},
        {"term": "ESD", "expansion": "Electrostatic Discharge", "hint": "Static shock that damages components", "category": "Safety"},
        {"term": "ATX", "expansion": "Advanced Technology eXtended", "hint": "Common PC motherboard/power form factor", "category": "Hardware"},
        {"term": "POST", "expansion": "Power-On Self-Test", "hint": "Firmware diagnostics at startup", "category": "Troubleshooting"},
        {"term": "BSOD", "expansion": "Blue Screen of Death", "hint": "Windows stop error screen", "category": "Troubleshooting"},
        {"term": "APIPA", "expansion": "Automatic Private IP Addressing", "hint": "169.254.x.x self-assigned address", "category": "Networking"},
        {"term": "MAC", "expansion": "Media Access Control", "hint": "Hardware address on NIC", "category": "Networking"},
        {"term": "IPv4", "expansion": "Internet Protocol version 4", "hint": "32-bit address space", "category": "Networking"},
        {"term": "IPv6", "expansion": "Internet Protocol version 6", "hint": "128-bit address space", "category": "Networking"},
        {"term": "HDMI", "expansion": "High-Definition Multimedia Interface", "hint": "Audio/video digital connector", "category": "Mobile/IO"},
        {"term": "DisplayPort", "expansion": "DisplayPort", "hint": "Digital display interface from VESA", "category": "Mobile/IO"},
        {"term": "BYOD", "expansion": "Bring Your Own Device", "hint": "Personal devices accessing corporate resources", "category": "Mobile"},
        {"term": "MDM", "expansion": "Mobile Device Management", "hint": "Central policy control for mobile endpoints", "category": "Mobile"},
        {"term": "IaaS", "expansion": "Infrastructure as a Service", "hint": "Cloud VMs and networks you manage", "category": "Cloud"},
        {"term": "SaaS", "expansion": "Software as a Service", "hint": "Cloud-hosted applications", "category": "Cloud"},
        {"term": "PaaS", "expansion": "Platform as a Service", "hint": "Managed runtime for developers", "category": "Cloud"},
        {"term": "VDI", "expansion": "Virtual Desktop Infrastructure", "hint": "Hosted desktops from datacenter", "category": "Virtualization"},
        {"term": "Hyper-V", "expansion": "Microsoft Hyper-V", "hint": "Windows Type 1/2 hypervisor", "category": "Virtualization"},
        {"term": "TPM", "expansion": "Trusted Platform Module", "hint": "Hardware root of trust chip", "category": "Security"},
        {"term": "UEFI Secure Boot", "expansion": "Secure Boot", "hint": "Validates OS bootloader signatures", "category": "Security"},
        {"term": "LCD inverter", "expansion": "Inverter board", "hint": "Backlight power for some laptop screens", "category": "Mobile"},
        {"term": "SO-DIMM", "expansion": "Small Outline Dual In-Line Memory Module", "hint": "Compact RAM form for laptops", "category": "Hardware"},
        {"term": "ECC", "expansion": "Error-Correcting Code", "hint": "Memory that fixes single-bit errors", "category": "Hardware"},
    ],
}

def write_fact_banks(path: Path, banks: dict) -> None:
    lines = [
        '"""CompTIA practice fact banks (original items, not real exam questions)."""',
        "from __future__ import annotations",
        "",
        "FACT_BANKS: dict[str, dict[str, list]] = {",
    ]
    for exam_id, domains in banks.items():
        lines.append(f'    "{exam_id}": {{')
        for domain_id, facts in domains.items():
            lines.append(f'        "{domain_id}": [')
            for fact in facts:
                lines.append(f"            {fact!r},")
            lines.append("        ],")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_acronyms(path: Path, data: dict) -> None:
    lines = [
        '"""CompTIA acronym glossary for practice exams."""',
        "from __future__ import annotations",
        "",
        "ACRONYMS_BY_EXAM: dict[str, list[dict[str, str]]] = {",
    ]
    for exam_id, items in data.items():
        lines.append(f'    "{exam_id}": [')
        for item in items:
            lines.append(f"        {item!r},")
        lines.append("    ],")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    write_fact_banks(OUT_DIR / "comptia_fact_banks.py", FACT_BANKS)
    write_acronyms(OUT_DIR / "comptia_acronyms.py", ACRONYMS)
    print("Wrote partial banks — run part 2 to complete remaining exams")
