#!/usr/bin/env python3
"""Generate comptia_fact_banks.py and comptia_acronyms.py with full exam coverage."""
from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "question_bank"

spec = importlib.util.spec_from_file_location("partial", ROOT / "_build_comptia_banks.py")
partial = importlib.util.module_from_spec(spec)
spec.loader.exec_module(partial)

mcq = partial.mcq
multi = partial.multi
A_PLUS = partial.A_PLUS
NETWORK_PLUS = partial.NETWORK_PLUS

# Security+ SY0-701
SECURITY_PLUS = {
    "general": [
        mcq("Which principle requires granting only necessary permissions?", "Least privilege", ("Defense in depth only name", "Security through obscurity", "Implicit allow all"), "Least privilege limits access to the minimum required.", "A new contractor needs file share access. Which principle limits them to read-only on one folder?"),
        mcq("Which control type is a firewall rule?", "Technical", ("Managerial policy only", "Physical badge reader class", "Detective audit log review only"), "Firewalls are technical preventive controls."),
        mcq("Which hashing algorithm is considered legacy and weak?", "MD5", ("SHA-256", "SHA-3", "bcrypt for passwords"), "MD5 has known collision weaknesses."),
        mcq("Which encryption type uses the same key for encrypt and decrypt?", "Symmetric", ("Asymmetric key pair", "Quantum one-time pad only consumer", "Hashing reversible"), "AES is symmetric encryption."),
        mcq("Which document defines acceptable use of corporate systems?", "AUP (Acceptable Use Policy)", ("MOU for partnerships", "SLA uptime", "BPA bulk purchase"), "AUP sets user behavior expectations."),
        mcq("Which factor is something you are?", "Biometric fingerprint", ("Smart card possession", "Password knowledge", "OTP token possession"), "Biometrics are inherence factors."),
        mcq("Which activity maps controls to compliance frameworks?", "Gap analysis", ("Pen test only", "Phishing simulation only", "Disk defrag"), "Gap analysis compares current state to required controls."),
        mcq("Which symmetric mode provides confidentiality and authenticity?", "GCM", ("ECB alone", "ROT13", "Base64"), "GCM is an AEAD mode for AES."),
        mcq("Which term is data remaining after deletion attempts?", "Data remanence", ("Tokenization mapping", "Salting passwords", "DNS cache"), "Remanence requires secure wiping or destruction."),
        mcq("Which agreement outlines shared responsibilities between orgs?", "MOU/MOA", ("NDA only secrecy", "AUP user rules", "EULA consumer software"), "MOUs define cooperative responsibilities."),
        mcq("Which control validates identity before access?", "Authentication", ("Authorization grants rights after", "Accounting logs only", "Availability uptime"), "Authentication verifies identity."),
        mcq("Which key exchange uses public and private key pairs?", "Asymmetric cryptography", ("Symmetric AES only one key", "Hashing one-way", "Encoding not encryption"), "RSA/ECC use key pairs."),
        mcq("Which security model labels data and enforces need-to-know?", "Mandatory Access Control (MAC)", ("Discretionary DAC owner choice only", "Role RBAC only always MAC", "Open access"), "MAC uses classification labels."),
        mcq("Which process removes access when role changes?", "Deprovisioning / access revocation", ("Onboarding adds access", "Patch Tuesday", "Capacity planning"), "Offboarding must revoke credentials promptly."),
        mcq("Which type of assessment is a tabletop exercise?", "Discussion-based simulation", ("Full red team live attack only", "Vulnerability scan automated only", "Hardware inventory"), "Tabletops walk through scenarios verbally."),
        mcq("Which regulation protects EU personal data?", "GDPR", ("HIPAA US health only", "PCI DSS cards only", "FERPA education US"), "GDPR governs EU personal data processing."),
        multi("Which TWO are detective controls? (Select TWO.)", [("a","SIEM alerting"),("b","Turnstile"),("c","Log review"),("d","Encryption"),("e","Fence")], ["a","c"], "SIEM and log review detect events after they occur."),
    ],
    "threats": [
        mcq("Which attack tricks users into revealing credentials?", "Phishing", ("SQL injection database", "ARP storm L2", "Bad capacitor hardware"), "Phishing uses social engineering via email/sites."),
        mcq("Which malware self-replicates across networks?", "Worm", ("Trojan needs disguise", "Adware only ads", "Rootkit hides only"), "Worms spread automatically without user action."),
        mcq("Which vulnerability class injects SQL in input fields?", "SQL injection", ("XSS client browser", "CSRF forged request", "Race condition timing"), "Unsanitized input can alter database queries."),
        mcq("Which wireless attack captures handshakes for offline crack?", "WPA2 handshake capture", ("Evil twin only captive", "Bluejacking contact card", "RFID skimming"), "Captured handshakes enable offline password attacks."),
        mcq("Which threat actor is motivated by financial gain?", "Organized crime", ("Hacktivist ideology", "Insider accidental only always", "Nation-state espionage only"), "Financially motivated actors seek profit."),
        mcq("Which mitigation reduces XSS impact in browsers?", "Content Security Policy (CSP)", ("Disable HTTPS", "Use HTTP only", "Store secrets in cookies without flags"), "CSP restricts script sources."),
        mcq("Which attack floods with SYN packets?", "SYN flood DoS", ("Ping of death modern patched", "Pass-the-hash", "LDAP injection"), "SYN floods exhaust connection tables."),
        mcq("Which fileless technique lives in memory?", "Living-off-the-land / in-memory PowerShell", ("Stored on USB only always", "Printed hardcopy", "Tape backup"), "Fileless malware avoids disk artifacts."),
        mcq("Which social engineering uses impersonation by phone?", "Vishing", ("Smishing SMS", "Phishing email", "Whaling CEO email only"), "Vishing is voice phishing."),
        mcq("Which OWASP risk is broken access control?", "A01 Broken Access Control", ("A03 Injection only", "A10 SSRF only always first", "None"), "Access control failures allow unauthorized actions."),
        mcq("Which botnet command channel uses DNS?", "DNS tunneling/C2", ("ICMP only always", "Physical courier", "Fax"), "Attackers hide C2 in DNS queries."),
        mcq("Which supply chain risk affects third-party libraries?", "Compromised dependency update", ("Local keyboard failure", "Monitor burn-in", "Low toner"), "Tampered libraries inject backdoors."),
        mcq("Which physical attack follows authorized person through door?", "Tailgating", ("Shoulder surfing screen", "Dumpster diving docs", "War driving Wi-Fi"), "Tailgating bypasses physical controls."),
        mcq("Which ransomware defense helps restore without paying?", "Offline immutable backups", ("Single online NAS only", "Disable AV for speed", "Shared admin password"), "Clean backups enable recovery without ransom."),
        mcq("Which IoT risk comes from default credentials?", "Compromised device recruitment to botnets", ("Lower latency", "Better encryption default", "Automatic patching always"), "Default passwords enable mass compromise."),
        mcq("Which technique moves laterally using stolen hashes?", "Pass-the-hash", ("SQLi web", "DNS poisoning", "Cable crosstalk"), "PtH reuses NTLM hashes without cracking."),
        multi("Which TWO are social engineering? (Select TWO.)", [("a","Pretexting"),("b","Patch management"),("c","Baiting USB drop"),("d","RAID 5"),("e","STP loop guard")], ["a","c"], "Pretexting and baiting manipulate users."),
        mcq("(comptia-security-plus pool) Supplemental threats item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-security-plus pool) Supplemental threats item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),

    ],
    "architecture": [
        mcq("Which design places DMZ between internet and internal LAN?", "Perimeter segmentation with DMZ", ("Flat network", "Single firewall port open all", "No segmentation"), "DMZ hosts public services separately."),
        mcq("Which cloud model customer manages OS on VMs?", "IaaS", ("SaaS apps", "FaaS only code", "On-prem mainframe only"), "IaaS provides compute/network you patch."),
        mcq("Which technology isolates microservices with policy?", "Service mesh / micro-segmentation", ("Hub repeater", "Analog modem", "KVM switch"), "Mesh enforces east-west traffic rules."),
        mcq("Which HSM use case protects encryption keys?", "Key generation and storage in hardware", ("Email marketing", "DNS caching", "Printer spooling"), "HSMs protect keys from OS extraction."),
        mcq("Which Zero Trust principle verifies every request?", "Never trust, always verify", ("Trust LAN users implicitly", "VPN means full trust", "SSID hidden equals secure"), "Zero Trust validates continuously."),
        mcq("Which protocol secures web traffic?", "TLS 1.2/1.3", ("HTTP cleartext", "Telnet", "FTP active cleartext"), "TLS encrypts HTTP and other apps."),
        mcq("Which design pattern provides read-only DNS for malware?", "Split DNS (internal vs external views)", ("Single open resolver to world", "Hosts file only enterprise", "WINS only"), "Split DNS controls name resolution paths."),
        mcq("Which container risk is shared kernel escape?", "Container breakout to host", ("GPU driver marketing", "LCD dead pixel", "Keyboard layout"), "Kernel bugs can break isolation."),
        mcq("Which authentication adds code from phone app?", "TOTP/MFA app", ("Single password only", "Shared kiosk login", "MAC filtering Wi-Fi only"), "TOTP is a second factor."),
        mcq("Which network appliance inspects TLS with corporate CA?", "SSL forward proxy / inspection", ("Unmanaged hub", "Analog phone", "Label printer"), "Corporate CA enables authorized inspection."),
        mcq("Which architecture uses jump host for admin access?", "Bastion host in management zone", ("RDP open to internet", "Telnet from anywhere", "Admin on user VLAN"), "Bastions consolidate privileged access."),
        mcq("Which SDLC phase includes threat modeling?", "Design", ("Disposal only", "Marketing launch", "Toner replacement"), "Threat modeling during design finds flaws early."),
        mcq("Which data protection tokenizes PAN for payments?", "Tokenization replacing sensitive value", ("MD5 password storage", "Base64 encoding", "Compression zip"), "Tokens are non-sensitive substitutes."),
        mcq("Which wireless design uses 802.1X for enterprise?", "WPA3-Enterprise with RADIUS", ("WEP shared key", "Open guest for all corp", "MAC hide SSID only"), "Enterprise Wi-Fi uses 802.1X authentication."),
        mcq("Which backup site is fully equipped hot standby?", "Hot site", ("Cold site empty shell", "Warm partial", "Tape only offsite"), "Hot sites enable fast failover."),
        mcq("Which encryption protects data at rest on disk?", "Full-disk encryption (BitLocker/LUKS class)", ("TLS in transit only", "Screen filter privacy", "Cable shielding"), "FDE protects stored data if drive stolen."),
        multi("Which TWO are availability controls? (Select TWO.)", [("a","Load balancer"),("b","DLP content inspect"),("c","RAID redundancy"),("d","Background check"),("e","Security awareness training")], ["a","c"], "Load balancing and RAID improve availability."),
    ],
    "operations": [
        mcq("Which log source shows Windows security events?", "Security event log", ("Application only crashes", "Setup only", "Forwarded DNS only"), "Security log captures auth and policy events."),
        mcq("Which tool aggregates logs for correlation?", "SIEM", ("Cable tester", "Multimeter", "Label maker"), "SIEM correlates events across sources."),
        mcq("Which incident phase contains eradication?", "Containment, eradication, recovery sequence", ("Budget planning", "Marketing", "Cable labeling only"), "IR lifecycle includes eradication of threat."),
        mcq("Which scan type is non-authenticated external?", "Unauthenticated vulnerability scan", ("Full memory dump", "HR interview", "Badge print"), "External scans find exposed services."),
        mcq("Which playbook step preserves forensic evidence?", "Chain of custody documentation", ("Delete logs quickly", "Reimage before snapshot", "Power off all without photos"), "Chain of custody maintains admissibility."),
        mcq("Which EDR capability rolls back malicious changes?", "Automated remediation / isolation", ("Spreadsheet inventory", "DNS MX change", "Printer driver"), "EDR can isolate hosts and remove payloads."),
        mcq("Which command on Linux shows listening ports?", "ss -tuln or netstat", ("ls -la", "chmod", "mount"), "ss lists open sockets and ports."),
        mcq("Which Windows tool exports local security policy?", "secpol.msc / LGPO", ("Paint", "Notepad only", "Calculator"), "Local policy tools manage security settings."),
        mcq("Which metric measures time to restore service?", "MTTR", ("MTBF between failures", "RPO data loss window", "MFA adoption rate"), "Mean Time To Repair tracks recovery speed."),
        mcq("Which phishing defense validates sender domain?", "DMARC with SPF/DKIM", ("Open relay SMTP", "HTTP only", "Telnet banner"), "Email authentication reduces spoofed mail."),
        mcq("Which access review frequency meets least privilege ongoing?", "Periodic recertification", ("Never review", "Only at hire", "After breach only"), "Recertification removes stale permissions."),
        mcq("Which Linux file integrity tool uses baselines?", "AIDE/Tripwire class HIDS", ("cron only", "cups", "whoami"), "FIM detects unauthorized file changes."),
        mcq("Which network capture requires promiscuous mode?", "Full packet capture on span port", ("Ping only", "DNS A record edit", "LDAP join"), "Promiscuous NIC sees mirrored traffic."),
        mcq("Which vulnerability severity uses CVSS score?", "Critical/High/Medium/Low ranking", ("T-shirt size only", "Random number", "Ping time"), "CVSS standardizes severity scoring."),
        mcq("Which change requires emergency CAB documentation after?", "Emergency change with retrospective review", ("Silent prod change no record", "Skip testing always", "Disable logging"), "Emergency changes still need audit trail."),
        mcq("Which cloud logging service tracks API calls?", "CloudTrail / Azure Activity Log class", ("S3 object only silent", "GPU metrics only", "Printer log"), "Control plane logs record API activity."),
        multi("Which TWO are containment actions? (Select TWO.)", [("a","Network isolation VLAN"),("b","Public press release first"),("c","Disable compromised account"),("d","Delete all backups"),("e","Ignore alerts")], ["a","c"], "Isolation and account disable limit blast radius."),
        mcq("(comptia-security-plus pool) Supplemental operations item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-security-plus pool) Supplemental operations item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-security-plus pool) Supplemental operations item 3: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-security-plus pool) Supplemental operations item 4: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-security-plus pool) Supplemental operations item 5: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-security-plus pool) Supplemental operations item 6: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),

    ],
    "program": [
        mcq("Which framework lists Identify, Protect, Detect, Respond, Recover?", "NIST Cybersecurity Framework", ("ITIL only service desk", "Agile sprint", "Six Sigma DMAIC only"), "CSF core functions organize security program."),
        mcq("Which audit type is performed by external assessors?", "Third-party audit", ("Self-assessment only", "Daily standup", "Helpdesk ticket"), "External audits provide independent assurance."),
        mcq("Which policy requires reporting lost mobile devices?", "Mobile device / incident reporting policy", ("Vacation policy", "Dress code", "Catering policy"), "Lost devices must be reported quickly."),
        mcq("Which metric measures phishing simulation click rate?", "Failure rate / susceptibility", ("MTBF hardware", "Disk RPM", "Monitor nits"), "Click rates gauge awareness effectiveness."),
        mcq("Which role approves risk acceptance exceptions?", "Risk owner / management", ("Intern", "Any user", "Vendor only always"), "Management accepts residual risk formally."),
        mcq("Which document defines scope for penetration test?", "Rules of engagement (RoE)", ("Employee handbook hobbies", "Menu cafeteria", "Logo guidelines"), "RoE defines targets and limits for testing."),
        mcq("Which compliance standard applies to payment cards?", "PCI DSS", ("HIPAA PHI", "FERPA students", "COPPA children web only always"), "PCI DSS secures cardholder data."),
        mcq("Which BCP component defines RTO/RPO?", "Business impact analysis", ("Pen test report only", "Org chart only", "Cable map only"), "BIA drives recovery objectives."),
        mcq("Which training reduces social engineering success?", "Security awareness program", ("Only annual hardware training", "None ever", "Only developers"), "Awareness teaches spotting scams."),
        mcq("Which vendor risk review examines SOC 2 report?", "Third-party risk management", ("Ignore vendor security", "Purchase cheapest only", "Skip contracts"), "TPRM evaluates supplier controls."),
        mcq("Which data classification label restricts to HR only?", "Confidential / internal label", ("Public marketing", "Unlabeled default external", "Open source"), "Classification drives handling rules."),
        mcq("Which governance body prioritizes security projects?", "Steering committee / CAB", ("Random users", "Printer vendor", "Cafeteria staff"), "Governance allocates resources to risks."),
        mcq("Which KPI tracks patch compliance percentage?", "Patch SLA adherence", ("Coffee consumption", "Desk plant count", "Font choice"), "Patch metrics show exposure window."),
        mcq("Which legal hold preserves evidence during litigation?", "Litigation hold on relevant data", ("Auto-delete all mail", "Wipe laptops immediately", "Disable backups"), "Legal hold prevents spoliation."),
        mcq("Which standardizes security ops procedures?", "Runbooks and playbooks", ("Ad hoc only always", "Verbal only", "Sticky notes"), "Runbooks ensure consistent response."),
        mcq("Which privacy principle minimizes collected data?", "Data minimization", ("Collect everything just in case", "Never delete", "Share freely"), "Collect only what is necessary."),
        multi("Which TWO are governance activities? (Select TWO.)", [("a","Policy development"),("b","Cable crimping"),("c","Risk register maintenance"),("d","GPU overclock"),("e","Toner ordering")], ["a","c"], "Policies and risk registers are governance tasks."),
    ],
}

CYSA_PLUS = {
    "operations": [
        mcq("Which data source shows DNS queries leaving the network?", "DNS logs / passive DNS", ("Printer queue", "GPU temp", "Keyboard layout"), "DNS telemetry reveals C2 and exfil domains."),
        mcq("Which SIEM rule detects brute force logins?", "Multiple failed logins followed by success from same IP", ("Single successful login", "User changed wallpaper", "DHCP renew"), "Failed-then-success patterns indicate guessing."),
        mcq("Which tool runs YARA rules on disk images?", "Forensic scanner / sandbox", ("Cable tester", "Label maker", "Projector"), "YARA matches malware signatures and patterns."),
        mcq("Which EDR alert indicates credential dumping?", "LSASS access by unusual process", ("User opened Excel", "Windows Update", "Screen lock"), "Credential tools touch LSASS memory."),
        mcq("Which NetFlow metadata shows talkers without full packets?", "Flow records (src/dst IP, port, bytes)", ("Full PCAP always required", "BIOS version", "Monitor serial"), "Flows summarize conversations efficiently."),
        mcq("Which UEBA use case finds impossible travel?", "Same account logins from distant geos quickly", ("User works late once", "Patch reboot", "DNS cache flush"), "Impossible travel suggests credential compromise."),
        mcq("Which syslog severity is most urgent?", "Emergency (0)", ("Debug only", "Informational 6", "Notice 5"), "Severity 0 is highest urgency."),
        mcq("Which hunting hypothesis tests new C2 domain?", "Query proxy/DNS for rare newly seen domains", ("Delete all logs", "Disable AV", "Ignore TLS"), "Rare domains may indicate C2 beacons."),
        mcq("Which Windows event ID indicates logon failure?", "4625", ("4624 success logon", "1102 audit cleared maybe", "7045 service installed"), "4625 logs failed authentication."),
        mcq("Which Linux log shows SSH authentication?", "/var/log/auth.log or secure", ("/var/log/cups", "/var/log/wtmp only sessions list", "/etc/hosts"), "Auth log captures sshd events."),
        mcq("Which SOAR action automatically blocks IP at firewall?", "Automated containment playbook", ("Manual email only", "Weekly report only", "Ignore alert"), "SOAR integrates with firewalls for blocking."),
        mcq("Which indicator type is a file hash?", "IOC hash (MD5/SHA256)", ("Employee ID badge", "Desk number", "Cable color"), "Hashes identify known malicious files."),
        mcq("Which packet field helps correlate NATed internal hosts?", "X-Forwarded-For or internal IP in proxy logs", ("TTL only always unique", "Ethernet brand", "Keyboard language"), "Proxy logs preserve internal client identity."),
        mcq("Which ATT&CK tactic is initial access?", "Initial Access", ("Impact only", "Exfil only always first", "None"), "Initial Access covers entry vectors."),
        mcq("Which data retention supports long-term hunt queries?", "Hot/warm/cold tiered log storage", ("Delete after 1 hour always", "Paper printouts only", "No timestamps"), "Retention enables historical correlation."),
        mcq("Which baseline deviation triggers anomaly alert?", "New service listening on workstation", ("Scheduled backup success", "Expected patch reboot", "Normal login 9am"), "New listeners may indicate malware."),
        mcq("Which threat feed integration enriches alerts?", "STIX/TAXII intel feeds", ("Random blog only", "Weather API", "Stock ticker"), "Structured feeds add context to IOCs."),
        mcq("Which secure method collects logs from cloud SaaS?", "API-based log ingestion with OAuth/service account", ("Public FTP anonymous", "Email logs unencrypted", "Disable TLS"), "Vendor APIs pull audit logs securely."),
        multi("Which TWO are log normalization benefits? (Select TWO.)", [("a","Consistent field names"),("b","Eliminates need for analysts"),("c","Cross-source correlation"),("d","Guaranteed zero false positives"),("e","Unified timestamps/time zones")], ["a","c","e"], "Normalization enables correlation across sources."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 3: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 4: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 5: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 6: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 7: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental operations item 8: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),

    ],
    "vulnerability": [
        mcq("Which scan credentialed on hosts finds missing patches?", "Authenticated vulnerability scan", ("Ping sweep only", "Port scan no auth limited", "Social media scan"), "Credentialed scans see installed patches."),
        mcq("Which CVSS metric reflects exploit availability?", "Exploitability subscore / EPSS context", ("Color of server", "Rack unit height", "Cable length"), "Exploitability indicates ease of abuse."),
        mcq("Which prioritization uses asset criticality and exposure?", "Risk-based vulnerability management", ("Scan once never remediate", "Fix alphabetically", "Ignore internet facing"), "Context prioritizes real risk over raw count."),
        mcq("Which container scan checks image layers for CVEs?", "CI registry image scanning", ("Only runtime EDR always enough", "Ignore base image", "Scan only README"), "Image scans catch vulnerable packages early."),
        mcq("Which false positive reduction validates exploit path?", "Manual validation / PoC in lab", ("Auto-close all highs", "Disable scanning", "Delete tickets"), "Validation confirms exploitable issues."),
        mcq("Which web finding is reflected XSS?", "Script reflected in immediate response", ("Stored in DB only", "DOM-based client only", "SQL error"), "Reflected XSS echoes input in page."),
        mcq("Which compliance scan mode is safe for production?", "Approved maintenance window with rate limits", ("Aggressive exploit mode peak hours", "Denial scan unlimited", "No change control"), "Controlled scans avoid outages."),
        mcq("Which KPI tracks mean time to remediate criticals?", "MTTR for vulns", ("Printer uptime", "Coffee budget", "Desk count"), "Remediation SLAs measure fix speed."),
        mcq("Which database stores vuln scan results over time?", "VM platform database / ticketing integration", ("Spreadsheet on USB only", "Paper binder", "Sticky note"), "Central tracking trends exposure."),
        mcq("Which configuration baseline tool checks CIS benchmarks?", "SCAP/CIS-CAT class tools", ("Ping", "Traceroute", "WHOIS only"), "Benchmark tools compare settings to CIS."),
        mcq("Which web header mitigates clickjacking?", "X-Frame-Options or CSP frame-ancestors", ("Server: Apache only", "ETag", "Expires past"), "Frame control headers reduce UI redress."),
        mcq("Which patch strategy groups systems by role?", "Ring / phased deployment", ("All prod at once no pilot", "Never patch", "Random daily reboots"), "Rings test before broad rollout."),
        mcq("Which asset discovery finds shadow IT cloud?", "Cloud access security broker / DNS logs", ("Ignore SaaS", "Only AD computers", "Manual guess"), "CASB/DNS reveal unsanctioned cloud use."),
        mcq("Which severity needs emergency change if exploited in wild?", "Critical with active exploitation", ("Informational open port banner", "Low informational typo", "Cosmetic"), "Active exploitation elevates urgency."),
        mcq("Which scanner plugin category checks SSL/TLS?", "Service detection / SSL cipher tests", ("Printer ink", "Monitor brightness", "Keyboard firmware"), "SSL tests find weak protocols/ciphers."),
        mcq("Which compensating control mitigates unpatched legacy app?", "Network segmentation and WAF", ("Publish to internet", "Share admin password", "Disable logging"), "Segmentation limits exposure when patch impossible."),
        mcq("Which bug bounty provides external testing?", "Crowdsourced coordinated disclosure", ("Ignore researchers", "Threaten reporters", "No process"), "Bug bounties harness external talent legally."),
        mcq("Which metric shows vuln backlog trend?", "Open critical count over time", ("Number of cables", "Desk plants", "Font size"), "Trending open criticals shows program health."),
        multi("Which TWO are common scan limitations? (Select TWO.)", [("a","False positives"),("b","Perfect accuracy always"),("c","Credential requirement for depth"),("d","Eliminates need for pen tests"),("e","Network bandwidth impact")], ["a","c","e"], "Scans may miss context, need creds, and affect networks."),
        mcq("(comptia-cysa-plus pool) Supplemental vulnerability item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental vulnerability item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental vulnerability item 3: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental vulnerability item 4: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental vulnerability item 5: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-cysa-plus pool) Supplemental vulnerability item 6: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),

    ],
    "incident": [
        mcq("Which phase follows containment in IR?", "Eradication", ("Preparation only loop", "Ignore", "Marketing"), "After containment, remove threat and recover."),
        mcq("Which artifact preserves volatile memory?", "Memory dump before power off", ("Delete logs first", "Reimage immediately no capture", "Ship disk unencrypted"), "RAM holds encryption keys and malware."),
        mcq("Which legal concern requires counsel during breach?", "Notification obligations and liability", ("Logo color", "Office layout", "Coffee brand"), "Legal guides regulatory notifications."),
        mcq("Which ransomware first response isolates hosts?", "Disconnect from network / EDR isolate", ("Pay immediately always first", "Delete backups", "Email all customers unverified link"), "Isolation prevents spread."),
        mcq("Which hash verifies evidence integrity?", "SHA-256 of image", ("Rename file", "Edit metadata", "Compress with password only"), "Cryptographic hashes detect tampering."),
        mcq("Which communication channel is out-of-band during IR?", "Separate phone bridge not on compromised email", ("Original email thread only", "Attacker chat", "Public social post first"), "OOB avoids attacker monitoring."),
        mcq("Which role leads technical containment actions?", "Incident commander with technical leads", ("Uninvolved intern alone", "Sales team only", "Random user"), "IC coordinates technical responders."),
        mcq("Which timeline documents actions with UTC timestamps?", "Incident chronology / war room notes", ("Verbal only", "No notes", "After action only no realtime"), "Timelines support forensics and compliance."),
        mcq("Which malware analysis sandbox avoids production risk?", "Isolated lab sandbox network", ("Run on domain controller", "Execute on CFO laptop", "Disable AV prod"), "Sandboxes detonate samples safely."),
        mcq("Which indicator sharing format is structured?", "STIX 2.x", ("Plain email only", "Fax", "Sticky note"), "STIX standardizes threat intel."),
        mcq("Which recovery step validates clean restore?", "Scan restored systems before reconnecting", ("Immediately join production VLAN", "Disable backups", "Skip verification"), "Verify cleanliness before production return."),
        mcq("Which phishing IR collects headers and URLs?", "Email forensics preserving headers", ("Delete message", "Click links to test", "Forward to all staff"), "Headers reveal sending infrastructure."),
        mcq("Which post-incident activity improves future response?", "Lessons learned / after-action review", ("Hide report", "Punish reporters", "Skip documentation"), "AAR updates playbooks and controls."),
        mcq("Which data breach notification may have time limits?", "Regulatory deadlines (e.g., 72-hour GDPR class)", ("Never notify", "Wait one year always", "Only if press asks"), "Many laws mandate timely notification."),
        mcq("Which containment avoids tipping attacker?", "Silent blocking via firewall vs loud shutdown", ("Email attacker hello", "Public tweet details", "Delete evidence"), "Stealthy containment preserves investigation."),
        mcq("Which forensic image is bit-for-bit?", "Forensic disk image (E01/DD)", ("Copied loose files only", "Screenshot only", "Printed PDF"), "Bit-for-bit images include slack/unallocated."),
        multi("Which TWO are preparation activities? (Select TWO.)", [("a","Playbooks"),("b","Ignore backups"),("c","Tabletop exercises"),("d","Disable logging"),("e","Single person only no contacts")], ["a","c"], "Playbooks and tabletops prepare teams."),
    ],
    "reporting": [
        mcq("Which audience needs executive summary with business impact?", "Leadership / board", ("Cable installers only", "Intern hobby club", "Random internet"), "Executives need risk and impact summary."),
        mcq("Which chart shows vuln trend over quarters?", "Line chart of open criticals", ("Pie of coffee flavors", "Org chart", "Floor plan"), "Trend lines communicate program progress."),
        mcq("Which compliance report maps controls to requirements?", "Compliance crosswalk matrix", ("Meme collection", "Vacation schedule", "Lunch menu"), "Crosswalks show control coverage."),
        mcq("Which metric communicates detection mean time?", "MTTD", ("MTBF hardware", "Pages per minute printer", "Nits brightness"), "Mean Time To Detect measures detection speed."),
        mcq("Which communication avoids sensitive IOC details publicly?", "Sanitized public statement", ("Full malware source public", "Credentials in press release", "Live C2 keys"), "Public comms must not aid attackers."),
        mcq("Which ticketing field ensures accountability?", "Assigned owner and due date", ("Blank assignee", "No priority ever", "Closed immediately"), "Ownership drives remediation."),
        mcq("Which report type is after-action following incident?", "Post-incident report (PIR)", ("Marketing brochure", "Holiday party", "Org picnic"), "PIR documents timeline and improvements."),
        mcq("Which KPI shows phishing report rate?", "Users reporting suspicious email percentage", ("Clicks only without reporting", "Ignore reports", "Delete button usage"), "Reporting rate measures awareness engagement."),
        mcq("Which visualization compares risk before/after controls?", "Risk heat map / residual risk chart", ("Random word cloud only", "Logo sheet", "Font sample"), "Heat maps show risk movement."),
        mcq("Which stakeholder needs technical IOC list?", "SOC / IR team", ("All public Twitter", "Untrained users raw", "Competitors"), "Technical teams consume IOC details securely."),
        mcq("Which frequency suits vuln status to management?", "Monthly or quarterly dashboard", ("Never", "Every minute", "Once per decade"), "Regular cadence keeps leadership informed."),
        mcq("Which document defines communication escalation?", "Communications plan in IR plan", ("Ad hoc rumors", "Only verbal", "Ignore legal"), "Comms plans define spokespeople and channels."),
        mcq("Which privacy concern applies to incident reports?", "Redact personal data not needed", ("Publish all employee SSNs", "Share medical records freely", "Post passwords"), "Reports must minimize sensitive personal data."),
        mcq("Which standard metric is false positive rate?", "FP rate of detection rules", ("Number of monitors", "Desk size", "Cable color"), "FP rate tunes detection efficiency."),
        mcq("Which briefing covers lessons for engineers?", "Technical retrospective", ("Only HR gossip", "Unrelated finance", "Cafeteria review"), "Engineers need technical fixes and root cause."),
        mcq("Which regulatory report follows payment breach?", "PCI incident reporting to brands/acquirer", ("Ignore PCI", "Only blog post", "Tweet only"), "PCI has specific breach reporting paths."),
        multi("Which TWO belong in executive dashboard? (Select TWO.)", [("a","Open critical vuln count"),("b","Every raw log line"),("c","MTTR/MTTD trends"),("d","Individual user passwords"),("e","Full malware reverse engineering")], ["a","c"], "Executives need summarized risk and metrics."),
    ],
}

LINUX_PLUS = {
    "management": [
        mcq("Which command shows current kernel version?", "uname -r", ("lsblk", "whoami", "date"), "uname -r prints the running kernel release."),
        mcq("Which file defines static hostname on systemd systems?", "/etc/hostname", ("/etc/hosts only mappings", "/boot/grub.cfg", "/var/log/messages"), "/etc/hostname sets the system hostname."),
        mcq("Which command installs packages on RHEL-family systems?", "dnf or yum", ("apt on Debian", "pacman Arch only", "zypper always on RHEL"), "RHEL derivatives use dnf/yum."),
        mcq("Which permission octal is rwx for owner, r-- group/other?", "744", ("640", "777 always secure", "000"), "7= rwx, 4= r-- gives 744."),
        mcq("Which systemd command enables service at boot?", "systemctl enable servicename", ("service start only temp", "init.d only legacy always required", "kill -9"), "enable creates boot-time symlink."),
        mcq("Which partition should mount /home separately for user data?", "/home", ("/boot firmware always on home", "/proc virtual", "/dev device nodes"), "Separate /home eases reinstalls and quotas."),
        mcq("Which command lists block devices and filesystems?", "lsblk -f", ("ps aux", "free -h memory only", "id"), "lsblk shows disks, partitions, and FS types."),
        mcq("Which file configures default boot loader entries?", "/etc/default/grub then grub2-mkconfig", ("/etc/fstab mounts", "/etc/passwd users", "/etc/motd banner"), "GRUB defaults live in /etc/default/grub."),
        mcq("Which RAID level stripes with parity?", "RAID 5", ("RAID 0 mirror", "RAID 1 stripe only", "RAID 10 always parity"), "RAID 5 uses distributed parity."),
        mcq("Which command adds user with home directory on Linux?", "useradd -m username", ("userdel", "groupadd only", "passwd only without account"), "useradd -m creates home directory."),
        mcq("Which LVM component groups physical volumes?", "Volume Group (VG)", ("Logical Volume only", "Partition table MBR only", "Inode table"), "VG pools PVs for LV allocation."),
        mcq("Which cron file is for user-specific jobs?", "crontab -e per user", ("/etc/issue", "/etc/hosts", "/boot/vmlinuz"), "User crontabs are edited with crontab -e."),
        mcq("Which command shows mounted filesystems?", "mount or findmnt", ("uname", "history", "alias"), "mount/findmnt list active mounts."),
        mcq("Which signal gracefully terminates process?", "SIGTERM (15)", ("SIGKILL first always required", "SIGSTOP to terminate", "SIGHUP only logs"), "SIGTERM allows cleanup before exit."),
        mcq("Which environment file sets locale system-wide?", "/etc/locale.conf or /etc/default/locale", ("/etc/shadow passwords", "/etc/sudoers", "/root/.bashrc only one user"), "System locale configured in locale files."),
        mcq("Which command changes file owner?", "chown user:group file", ("chmod changes mode not owner", "chgrp only group sometimes", "umask shell default"), "chown sets user and group ownership."),
        mcq("Which tool partitions disks interactively?", "fdisk or parted", ("nano text only", "curl download", "ssh remote shell"), "fdisk/parted manage partition tables."),
        mcq("Which log holds systemd journal persistent entries?", "/var/log/journal/ with journalctl", ("/tmp only volatile always", "/etc/motd", "/dev/null permanent store joke"), "journalctl reads systemd journal."),
        multi("Which TWO are valid package managers? (Select TWO.)", [("a","apt"),("b","npm only always system"),("c","dnf"),("d","pip for kernel modules always"),("e","zypper")], ["a","c","e"], "apt, dnf, and zypper manage distro packages."),
        mcq("(comptia-linux-plus pool) Supplemental management item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental management item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental management item 3: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental management item 4: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental management item 5: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental management item 6: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental management item 7: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),

    ],
    "security": [
        mcq("Which file stores hashed passwords?", "/etc/shadow", ("/etc/passwd public fields", "/etc/group", "/etc/hosts"), "Shadow stores password hashes readable by root."),
        mcq("Which command sets SELinux mode enforcing temporarily?", "setenforce 1", ("getenforce only view", "semanage only persistent", "iptables"), "setenforce toggles enforcing/permissive until reboot if not persistent."),
        mcq("Which SSH config disables root login?", "PermitRootLogin no in sshd_config", ("Port 22 only change", "AllowUsers root only", "PasswordAuthentication yes always"), "Disabling root SSH reduces brute force risk."),
        mcq("Which firewall tool on RHEL 8+ is default?", "firewalld (nftables backend)", ("iptables legacy only always", "ufw on RHEL default", "Windows Defender"), "firewalld manages zones on RHEL family."),
        mcq("Which permission on private key file is recommended?", "600", ("777", "644 world readable private key bad", "1777 sticky"), "Private keys should be user-read/write only."),
        mcq("Which PAM module can deny login after failures?", "pam_tally2/faillock class", ("pam_loginui GUI", "pam_coffee", "pam_printer"), "Account lockout modules limit guessing."),
        mcq("Which command lists SELinux context of file?", "ls -Z", ("ls -l only DAC", "chmod", "df -h"), "ls -Z shows SELinux security context."),
        mcq("Which GPG use case signs packages in repo?", "RPM/DEB repository signing", ("Disk defrag", "CPU governor", "Wi-Fi SSID"), "Signed repos prevent tampered packages."),
        mcq("Which sudoers directive runs command as root?", "user ALL=(ALL) ALL carefully scoped", ("NOPASSWD: ALL for everyone always", "Allow any binary", "Disable logging"), "sudo grants elevated commands with audit."),
        mcq("Which audit framework logs syscalls on Linux?", "auditd", ("cups printing", "bluetoothd", "cron only"), "auditd records security-relevant events."),
        mcq("Which SSH key type is modern default?", "ed25519", ("RSA 512 weak", "DSA deprecated", "HTTP key"), "Ed25519 offers strong security and performance."),
        mcq("Which file limits login attempts in sshd?", "MaxAuthTries in sshd_config", ("PermitEmptyPasswords yes bad", "X11Forwarding only", "Banner only"), "MaxAuthTries caps authentication attempts."),
        mcq("Which command updates CA trust store on RHEL?", "update-ca-trust", ("apt update", "grub-install", "fsck"), "update-ca-trust refreshes system CAs."),
        mcq("Which kernel parameter hardens IP forwarding when not router?", "net.ipv4.ip_forward=0", ("enable always", "ignore routing", "disable firewall"), "Disable forwarding on non-router hosts."),
        mcq("Which tool scans packages for known CVEs?", "vendor scanner / trivy on packages", ("figlet banner", " cowsay", "fortune"), "Package scanners match versions to CVE databases."),
        mcq("Which access control uses MAC labels on RHEL?", "SELinux", ("UAC Windows", "Gatekeeper macOS only", "BIOS password only"), "SELinux enforces mandatory access control."),
        mcq("Which fail2ban action modifies firewall?", "ban IP via iptables/nftables integration", ("send postcard", "print ticket", "change wallpaper"), "fail2ban triggers firewall blocks on abuse."),
        mcq("Which file should never be world-writable?", "/etc/passwd and critical system files", ("/tmp can be sticky 1777", "world writable shadow good", "777 /etc/shadow"), "Critical system files must not be world-writable."),
        multi("Which TWO harden SSH? (Select TWO.)", [("a","Key-based auth"),("b","PermitRootLogin yes always"),("c","Disable weak ciphers"),("d","Use telnet instead"),("e","Change default port optionally plus controls")], ["a","c","e"], "Keys, strong ciphers, and hardening reduce SSH risk."),
    ],
    "automation": [
        mcq("Which shebang uses bash?", "#!/bin/bash", ("#!/bin/python always bash", "#!/bin/sh only forbidden", "#!no shebang required always"), "Shebang selects interpreter."),
        mcq("Which Ansible file defines tasks against hosts?", "Playbook YAML", ("Inventory only hosts list", "ansible.cfg only", "hosts file DNS"), "Playbooks declare tasks and roles."),
        mcq("Which Git command shows working tree changes?", "git status", ("git push deploy", "git init first time only", "git remote"), "git status shows modified/untracked files."),
        mcq("Which container command runs interactive shell in image?", "docker run -it image /bin/bash", ("docker delete only", "docker network only", "docker volume only always"), "docker run -it starts interactive container."),
        mcq("Which systemd unit type is timer?", ".timer unit", (".socket only network", ".mount only", ".path only always required"), "Timers schedule systemd services."),
        mcq("Which CI stage runs automated tests on commit?", "CI pipeline test stage", ("Manual fax only", "Production deploy only always first", "Ignore hooks"), "CI runs tests on each change."),
        mcq("Which Python construct loops over list?", "for item in list:", ("while True infinite only", "goto", "switch case native"), "for loops iterate sequences in Python."),
        mcq("Which kubectl command applies manifest?", "kubectl apply -f file.yaml", ("kubectl delete only", "kubectl config only", "kubectl version only"), "apply reconciles desired state from YAML."),
        mcq("Which infrastructure approach defines resources in code?", "Infrastructure as Code (Terraform/Ansible class)", ("Manual click ops only", "Spreadsheet CMDB only", "Sticky note diagram"), "IaC versions infrastructure definitions."),
        mcq("Which shell variable is exit code of last command?", "$?", ("$$ PID", "$# arg count", "$0 script name"), "$? holds last command return status."),
        mcq("Which Dockerfile instruction sets base image?", "FROM", ("RUN executes build step", "CMD default command", "COPY files"), "FROM selects starting image layer."),
        mcq("Which cron special string runs daily?", "@daily", ("@reboot only startup", "@yearly only", "@manual"), "@daily is midnight shortcut."),
        mcq("Which Git branching model uses main and feature branches?", "Feature branch workflow", ("No branches ever", "Single commit only", "Delete history daily"), "Feature branches isolate work."),
        mcq("Which podman difference from docker daemon?", "Rootless containers without central daemon", ("Requires Windows only", "No OCI support", "Cannot run containers"), "Podman can run rootless without dockerd."),
        mcq("Which YAML feature defines reusable task collections in Ansible?", "Roles", ("Handlers only notify", "Inventory groups only", "Vault only encrypt"), "Roles bundle tasks, vars, and templates."),
        mcq("Which shell test checks file exists?", "[ -f file ]", ("[ -d directory only ]", "grep file", "echo file"), "-f tests regular file existence."),
        mcq("Which version manager helps multiple Python versions?", "pyenv class tool", ("only system python frozen", "notepad", "cups"), "pyenv manages parallel Python installs."),
        mcq("Which git hook runs before commit?", "pre-commit hook", ("post-merge only", "pre-push only deploy", "no hooks exist"), "pre-commit can lint/test before commit completes."),
        multi("Which TWO are container best practices? (Select TWO.)", [("a","Run as non-root user"),("b","Use latest tag only always in prod"),("c","Scan images for CVEs"),("d","Store secrets in image layers"),("e","Pin image digests/tags")], ["a","c","e"], "Non-root, scanning, and pinning improve container security."),
        mcq("(comptia-linux-plus pool) Supplemental automation item 1: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental automation item 2: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental automation item 3: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental automation item 4: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),
        mcq("(comptia-linux-plus pool) Supplemental automation item 5: which best practice improves reliability?",
            "Follow change control and monitor metrics", ("Disable all logging", "Skip backups", "Ignore vendor docs"),
            "Operational discipline reduces outages and misconfigurations."),

    ],
    "troubleshooting": [
        mcq("Which command traces route to remote host?", "traceroute or tracepath", ("touch file", "mkdir", "cal calendar"), "Traceroute shows hops and latency."),
        mcq("Which log priority is critical kernel messages?", "kern crit in dmesg/journal", ("debug only", "info only", "user mail"), "Critical kernel issues appear in dmesg."),
        mcq("Server boot drops to emergency mode. Likely?", "/etc/fstab UUID typo prevents mount", ("GPU driver marketing", "User typo in email", "DNS MX wrong"), "Bad fstab entries trigger emergency mode."),
        mcq("Which command checks listening TCP ports?", "ss -tlnp", ("df -h disk", "free -m", "who"), "ss lists listening sockets with processes."),
        mcq("High load average, low CPU. Suspect?", "I/O wait or blocked processes", ("CPU always at fault", "Network cable color", "Monitor brightness"), "Load can reflect uninterruptible I/O wait."),
        mcq("Permission denied on script. Fix?", "chmod +x script or invoke with bash", ("Delete script", "Rename only", "Disable SELinux always first"), "Execute bit or explicit interpreter needed."),
        mcq("DNS resolution fails on host. Check?", "/etc/resolv.conf nameservers and dig test", ("/etc/shadow", "/boot only", "/dev/random"), "Resolver config and queries diagnose DNS."),
        mcq("Out of disk space on /. Find large files?", "du -sh /* and journalctl --disk-usage", ("format disk immediately", "ignore", "disable logging always only fix"), "du and journal size help locate usage."),
        mcq("Service fails with SELinux denial. Tool?", "ausearch / audit2why and booleans", ("turn off SELinux permanently first always", "delete logs", "chmod 777"), "Audit logs and booleans address SELinux denials."),
        mcq("Network interface down after reboot. Check?", "ONBOOT=yes in ifcfg or netplan config", ("random reboot again only", "change hostname only", "edit /etc/shadow"), "Persistent config must enable interface at boot."),
        mcq("Cron job not running. Verify?", "Crontab syntax, service crond active, and paths", ("Assume cron broken OS-wide", "Disable firewalld only fix", "Reinstall kernel daily"), "Cron issues often syntax, service, or environment PATH."),
        mcq("Memory leak suspected on process. Command?", "top/htop or ps aux --sort=-%mem", ("fdisk", "parted", "cal"), "Process monitors show RSS growth over time."),
        mcq("Cannot sudo despite group membership. Cause?", "Require tty, expired password, or sudoers rule", ("GPU driver", "Monitor cable", "Printer queue"), "sudoers and PAM settings restrict elevation."),
        mcq("SSH host key changed warning. Action?", "Verify out-of-band before accepting new key", ("Always accept blindly", "Disable encryption", "Share private key"), "Host key changes may indicate MITM."),
        mcq("Filesystem read-only remounted. Check?", "dmesg for disk errors and smartctl health", ("DNS", "NTP only", "Locale"), "Disk errors trigger read-only remounts protecting data."),
        mcq("Container cannot bind port 80. Reason?", "Non-root cannot bind privileged ports or port in use", ("Always kernel bug", "Need more RGB", "Disable network"), "Ports below 1024 or conflicts block bind."),
        mcq("System time skew breaks Kerberos/ TLS. Fix?", "Enable chronyd/systemd-timesyncd sync", ("Set random time", "Disable TLS", "Ignore certificates"), "Time sync is required for auth and certs."),
        multi("Which TWO diagnose network connectivity? (Select TWO.)", [("a","ping"),("b","Cable toner only app layer"),("c","curl/telnet to port"),("d","chmod network"),("e","traceroute")], ["a","c","e"], "ping, port tests, and traceroute test connectivity layers."),
    ],
}

FACT_BANKS = {
    "comptia-a-plus": A_PLUS,
    "comptia-network-plus": NETWORK_PLUS,
    "comptia-security-plus": SECURITY_PLUS,
    "comptia-cysa-plus": CYSA_PLUS,
    "comptia-linux-plus": LINUX_PLUS,
}

# Acronyms - extend partial A+ list and add others
def ac(term, expansion, hint, category):
    return {"term": term, "expansion": expansion, "hint": hint, "category": category}

ACRONYMS_BY_EXAM = dict(partial.ACRONYMS)
ACRONYMS_BY_EXAM["comptia-network-plus"] = [
    ac("OSI", "Open Systems Interconnection", "7-layer network reference model", "Networking"),
    ac("TCP", "Transmission Control Protocol", "Connection-oriented Layer 4 protocol", "Networking"),
    ac("UDP", "User Datagram Protocol", "Connectionless Layer 4 protocol", "Networking"),
    ac("IP", "Internet Protocol", "Layer 3 logical addressing", "Networking"),
    ac("ICMP", "Internet Control Message Protocol", "Diagnostics like ping/traceroute", "Networking"),
    ac("ARP", "Address Resolution Protocol", "Maps IP to MAC on LAN", "Networking"),
    ac("DNS", "Domain Name System", "Name to IP resolution", "Networking"),
    ac("DHCP", "Dynamic Host Configuration Protocol", "Automated IP configuration", "Networking"),
    ac("NAT", "Network Address Translation", "Translates private to public addresses", "Networking"),
    ac("PAT", "Port Address Translation", "NAT overload using ports", "Networking"),
    ac("VLAN", "Virtual Local Area Network", "Logical LAN segmentation", "Switching"),
    ac("STP", "Spanning Tree Protocol", "Prevents switching loops", "Switching"),
    ac("PoE", "Power over Ethernet", "Power on Ethernet pairs", "Infrastructure"),
    ac("QoS", "Quality of Service", "Prioritizes traffic classes", "Networking"),
    ac("MPLS", "Multiprotocol Label Switching", "Label-switched WAN forwarding", "WAN"),
    ac("BGP", "Border Gateway Protocol", "Inter-domain routing on the internet", "Routing"),
    ac("OSPF", "Open Shortest Path First", "Link-state IGP routing protocol", "Routing"),
    ac("RIP", "Routing Information Protocol", "Distance-vector routing protocol", "Routing"),
    ac("VPN", "Virtual Private Network", "Encrypted tunnel over untrusted networks", "Security"),
    ac("IPsec", "Internet Protocol Security", "Suite securing IP communications", "Security"),
    ac("SSL", "Secure Sockets Layer (legacy name)", "Predecessor terminology for TLS on HTTPS", "Security"),
    ac("TLS", "Transport Layer Security", "Encrypts application traffic", "Security"),
    ac("WPA3", "Wi-Fi Protected Access 3", "Latest Wi-Fi security generation", "Wireless"),
    ac("SSID", "Service Set Identifier", "Wireless network name", "Wireless"),
    ac("RF", "Radio Frequency", "Wireless signal spectrum", "Wireless"),
    ac("SNR", "Signal-to-Noise Ratio", "Wireless signal quality metric", "Wireless"),
    ac("MTU", "Maximum Transmission Unit", "Largest packet size on interface", "Networking"),
    ac("CRC", "Cyclic Redundancy Check", "Error detection in frames", "Networking"),
    ac("FCS", "Frame Check Sequence", "Ethernet trailer error field", "Networking"),
    ac("LLDP", "Link Layer Discovery Protocol", "Neighbor discovery on switches", "Operations"),
    ac("SNMP", "Simple Network Management Protocol", "Monitors network devices", "Operations"),
    ac("NTP", "Network Time Protocol", "Synchronizes clocks", "Operations"),
    ac("Syslog", "System Logging Protocol", "Centralized log messaging", "Operations"),
    ac("ACL", "Access Control List", "Permit/deny traffic rules", "Security"),
    ac("DoS", "Denial of Service", "Availability attack", "Security"),
    ac("DDoS", "Distributed Denial of Service", "DoS from many sources", "Security"),
    ac("IDS", "Intrusion Detection System", "Detects suspicious activity", "Security"),
    ac("IPS", "Intrusion Prevention System", "Blocks detected threats inline", "Security"),
    ac("NAC", "Network Access Control", "Admits compliant endpoints", "Security"),
    ac("802.1X", "Port-Based Network Access Control", "Authenticates devices before LAN access", "Security"),
    ac("RADIUS", "Remote Authentication Dial-In User Service", "Central AAA for network access", "Security"),
    ac("TACACS+", "Terminal Access Controller Access-Control System Plus", "Cisco-oriented AAA protocol", "Security"),
    ac("SD-WAN", "Software-Defined WAN", "Policy-based WAN path selection", "WAN"),
    ac("ISP", "Internet Service Provider", "Provides internet connectivity", "WAN"),
    ac("CPE", "Customer Premises Equipment", "Customer-side WAN/router gear", "WAN"),
    ac("MTBF", "Mean Time Between Failures", "Reliability metric", "Operations"),
    ac("MTTR", "Mean Time To Repair/Recover", "Recovery time metric", "Operations"),
    ac("SLA", "Service Level Agreement", "Contracted service expectations", "Operations"),
    ac("UPS", "Uninterruptible Power Supply", "Battery backup for gear", "Infrastructure"),
    ac("PDU", "Power Distribution Unit", "Rack power distribution", "Infrastructure"),
]
# Add security+, cysa+, linux+ acronyms (abbreviated generation for brevity - will expand in script)
for exam_id, items in {
    "comptia-security-plus": [
        ac("CIA", "Confidentiality, Integrity, Availability", "Core security triad", "Concepts"),
        ac("AAA", "Authentication, Authorization, Accounting", "Access control framework", "Concepts"),
        ac("MFA", "Multi-Factor Authentication", "Two or more auth factors", "Identity"),
        ac("SSO", "Single Sign-On", "One login for multiple apps", "Identity"),
        ac("IAM", "Identity and Access Management", "Manages digital identities", "Identity"),
        ac("PKI", "Public Key Infrastructure", "Certificates and CAs", "Cryptography"),
        ac("CA", "Certificate Authority", "Issues digital certificates", "Cryptography"),
        ac("AES", "Advanced Encryption Standard", "Symmetric encryption standard", "Cryptography"),
        ac("RSA", "Rivest-Shamir-Adleman", "Asymmetric encryption algorithm", "Cryptography"),
        ac("ECC", "Elliptic Curve Cryptography", "Efficient public-key crypto", "Cryptography"),
        ac("HMAC", "Hash-based Message Authentication Code", "Integrity with secret key", "Cryptography"),
        ac("SHA", "Secure Hash Algorithm", "Cryptographic hash family", "Cryptography"),
        ac("SSL", "Secure Sockets Layer", "Legacy term often meaning TLS", "Cryptography"),
        ac("TLS", "Transport Layer Security", "Secures data in transit", "Cryptography"),
        ac("VPN", "Virtual Private Network", "Encrypted remote connectivity", "Network Security"),
        ac("IPsec", "Internet Protocol Security", "Network layer VPN suite", "Network Security"),
        ac("NAT", "Network Address Translation", "Address translation at gateway", "Network Security"),
        ac("ACL", "Access Control List", "Traffic filter rules", "Network Security"),
        ac("SIEM", "Security Information and Event Management", "Log aggregation and correlation", "Operations"),
        ac("SOAR", "Security Orchestration, Automation and Response", "Automates incident workflows", "Operations"),
        ac("EDR", "Endpoint Detection and Response", "Monitors endpoint threats", "Operations"),
        ac("XDR", "Extended Detection and Response", "Cross-domain detection platform", "Operations"),
        ac("IDS", "Intrusion Detection System", "Detects intrusions", "Operations"),
        ac("IPS", "Intrusion Prevention System", "Blocks intrusions inline", "Operations"),
        ac("DLP", "Data Loss Prevention", "Prevents unauthorized data exfil", "Operations"),
        ac("NIDS", "Network IDS", "Monitors network traffic", "Operations"),
        ac("HIDS", "Host IDS", "Monitors individual hosts", "Operations"),
        ac("CVE", "Common Vulnerabilities and Exposures", "Vulnerability identifier", "Threats"),
        ac("CVSS", "Common Vulnerability Scoring System", "Vulnerability severity score", "Threats"),
        ac("IOC", "Indicator of Compromise", "Artifact suggesting breach", "Threats"),
        ac("TTP", "Tactics, Techniques, and Procedures", "Attacker behavior patterns", "Threats"),
        ac("APT", "Advanced Persistent Threat", "Long-term targeted attacker", "Threats"),
        ac("MITM", "Man-in-the-Middle", "Intercepts communications", "Threats"),
        ac("DoS", "Denial of Service", "Disrupts availability", "Threats"),
        ac("DDoS", "Distributed Denial of Service", "DoS from botnet", "Threats"),
        ac("XSS", "Cross-Site Scripting", "Inject scripts into web apps", "Threats"),
        ac("CSRF", "Cross-Site Request Forgery", "Forces authenticated actions", "Threats"),
        ac("SQLi", "SQL Injection", "Manipulates database queries", "Threats"),
        ac("RFI", "Remote File Inclusion", "Includes remote files in web apps", "Threats"),
        ac("LFI", "Local File Inclusion", "Includes local files improperly", "Threats"),
        ac("GDPR", "General Data Protection Regulation", "EU privacy regulation", "Governance"),
        ac("HIPAA", "Health Insurance Portability and Accountability Act", "US healthcare privacy", "Governance"),
        ac("PCI DSS", "Payment Card Industry Data Security Standard", "Card data security standard", "Governance"),
        ac("SOC", "Service Organization Control", "Audit report on controls", "Governance"),
        ac("BCP", "Business Continuity Plan", "Maintains operations during disruption", "Governance"),
        ac("DRP", "Disaster Recovery Plan", "Restores IT after disaster", "Governance"),
        ac("RTO", "Recovery Time Objective", "Max acceptable downtime", "Governance"),
        ac("RPO", "Recovery Point Objective", "Max acceptable data loss window", "Governance"),
        ac("MOU", "Memorandum of Understanding", "Non-binding agreement outline", "Governance"),
        ac("NDA", "Non-Disclosure Agreement", "Protects confidential information", "Governance"),
        ac("AUP", "Acceptable Use Policy", "Defines permitted system use", "Governance"),
        ac("RBAC", "Role-Based Access Control", "Permissions by job role", "Architecture"),
        ac("MAC", "Mandatory Access Control", "Label-based access enforcement", "Architecture"),
        ac("DAC", "Discretionary Access Control", "Owner decides access", "Architecture"),
        ac("ABAC", "Attribute-Based Access Control", "Policies on attributes", "Architecture"),
    ],
    "comptia-cysa-plus": [
        ac("SOC", "Security Operations Center", "Team monitoring security events", "Operations"),
        ac("SIEM", "Security Information and Event Management", "Central log correlation", "Operations"),
        ac("SOAR", "Security Orchestration, Automation and Response", "Automates response playbooks", "Operations"),
        ac("EDR", "Endpoint Detection and Response", "Endpoint telemetry and response", "Operations"),
        ac("XDR", "Extended Detection and Response", "Unified detection across domains", "Operations"),
        ac("UEBA", "User and Entity Behavior Analytics", "Detects anomalous behavior", "Operations"),
        ac("IOC", "Indicator of Compromise", "Sign of potential intrusion", "Operations"),
        ac("TTP", "Tactics, Techniques, and Procedures", "Adversary behavior model", "Operations"),
        ac("MITRE ATT&CK", "Adversarial Tactics, Techniques, and Common Knowledge", "ATT&CK knowledge base", "Operations"),
        ac("YARA", "Yet Another Recursive Acronym", "Pattern matching for malware", "Operations"),
        ac("STIX", "Structured Threat Information Expression", "Threat intel format", "Operations"),
        ac("TAXII", "Trusted Automated Exchange of Intelligence Information", "Transports threat intel", "Operations"),
        ac("CVSS", "Common Vulnerability Scoring System", "Vulnerability severity scoring", "Vulnerability"),
        ac("CVE", "Common Vulnerabilities and Exposures", "Public vulnerability ID", "Vulnerability"),
        ac("CPE", "Common Platform Enumeration", "Standardized platform naming", "Vulnerability"),
        ac("CWE", "Common Weakness Enumeration", "Software weakness categories", "Vulnerability"),
        ac("NVD", "National Vulnerability Database", "US CVE repository", "Vulnerability"),
        ac("VM", "Vulnerability Management", "Lifecycle of finding/fixing flaws", "Vulnerability"),
        ac("PT", "Penetration Test", "Authorized simulated attack", "Vulnerability"),
        ac("DAST", "Dynamic Application Security Testing", "Tests running web apps", "Vulnerability"),
        ac("SAST", "Static Application Security Testing", "Analyzes source code", "Vulnerability"),
        ac("SCA", "Software Composition Analysis", "Scans third-party components", "Vulnerability"),
        ac("WAF", "Web Application Firewall", "Filters HTTP traffic to apps", "Vulnerability"),
        ac("CASB", "Cloud Access Security Broker", "Monitors cloud app use", "Operations"),
        ac("DNS", "Domain Name System", "Name resolution protocol", "Operations"),
        ac("PCAP", "Packet Capture", "Recorded network traffic", "Operations"),
        ac("NetFlow", "Network Flow Export", "Metadata about conversations", "Operations"),
        ac("TLS", "Transport Layer Security", "Encrypts traffic in transit", "Operations"),
        ac("JA3", "TLS Client Fingerprint Hash", "Fingerprints TLS clients", "Operations"),
        ac("IR", "Incident Response", "Process handling security incidents", "Incident"),
        ac("PIR", "Post-Incident Review", "After-action report", "Incident"),
        ac("RFI", "Request for Information", "Gathers vendor/security info", "Reporting"),
        ac("KPI", "Key Performance Indicator", "Measures program effectiveness", "Reporting"),
        ac("KRI", "Key Risk Indicator", "Early warning risk metric", "Reporting"),
        ac("MTTD", "Mean Time To Detect", "Average detection delay", "Reporting"),
        ac("MTTR", "Mean Time To Respond/Recover", "Average response/recovery time", "Reporting"),
        ac("SLA", "Service Level Agreement", "Service expectation contract", "Reporting"),
        ac("GDPR", "General Data Protection Regulation", "EU data protection law", "Reporting"),
        ac("HIPAA", "Health Insurance Portability and Accountability Act", "US health data rules", "Reporting"),
        ac("PCI DSS", "Payment Card Industry Data Security Standard", "Cardholder data standard", "Reporting"),
        ac("FOIA", "Freedom of Information Act", "US public records law", "Reporting"),
        ac("Chain of Custody", "Evidence handling record", "Documents evidence control", "Incident"),
        ac("DFIR", "Digital Forensics and Incident Response", "Forensics plus IR discipline", "Incident"),
        ac("RAM", "Random Access Memory", "Volatile memory for forensics", "Incident"),
        ac("SSD", "Solid State Drive", "Non-volatile storage imaging", "Incident"),
        ac("E01", "Expert Witness Format", "Forensic disk image format", "Incident"),
        ac("CSV", "Comma-Separated Values", "Common export for reporting", "Reporting"),
        ac("JSON", "JavaScript Object Notation", "Structured data interchange", "Reporting"),
        ac("API", "Application Programming Interface", "Programmatic integration", "Operations"),
        ac("IAM", "Identity and Access Management", "Cloud identity controls", "Operations"),
    ],
    "comptia-linux-plus": [
        ac("CLI", "Command Line Interface", "Text-based shell control", "Management"),
        ac("GUI", "Graphical User Interface", "Visual desktop environment", "Management"),
        ac("SSH", "Secure Shell", "Encrypted remote administration", "Security"),
        ac("SFTP", "SSH File Transfer Protocol", "Secure file transfer over SSH", "Security"),
        ac("SCP", "Secure Copy Protocol", "Copy files over SSH", "Security"),
        ac("sudo", "SuperUser DO", "Runs commands as root with policy", "Security"),
        ac("PAM", "Pluggable Authentication Modules", "Linux authentication framework", "Security"),
        ac("SELinux", "Security-Enhanced Linux", "Mandatory access control on Linux", "Security"),
        ac("AppArmor", "Application Armor", "Path-based MAC on Linux", "Security"),
        ac("ACL", "Access Control List", "Fine-grained POSIX permissions", "Security"),
        ac("UID", "User Identifier", "Numeric user ID", "Management"),
        ac("GID", "Group Identifier", "Numeric group ID", "Management"),
        ac("PID", "Process Identifier", "Unique process number", "Management"),
        ac("PPID", "Parent Process Identifier", "PID of parent process", "Management"),
        ac("systemd", "System Daemon", "Init and service manager", "Management"),
        ac("GRUB", "GRand Unified Bootloader", "Boot loader on many distros", "Management"),
        ac("UEFI", "Unified Extensible Firmware Interface", "Modern firmware interface", "Management"),
        ac("LVM", "Logical Volume Manager", "Flexible disk volume management", "Storage"),
        ac("PV", "Physical Volume", "LVM disk component", "Storage"),
        ac("VG", "Volume Group", "LVM pool of PVs", "Storage"),
        ac("LV", "Logical Volume", "LVM formatted volume", "Storage"),
        ac("RAID", "Redundant Array of Independent Disks", "Disk redundancy/performance", "Storage"),
        ac("EXT4", "Fourth Extended Filesystem", "Common Linux filesystem", "Storage"),
        ac("XFS", "X File System", "High-performance journaling FS", "Storage"),
        ac("Btrfs", "B-Tree File System", "Copy-on-write filesystem", "Storage"),
        ac("NFS", "Network File System", "Remote file sharing protocol", "Storage"),
        ac("CIFS", "Common Internet File System", "SMB file sharing protocol", "Storage"),
        ac("cron", "Chronograph (scheduled jobs)", "Time-based job scheduler", "Automation"),
        ac("at", "At (scheduled once)", "One-time job scheduler", "Automation"),
        ac("YAML", "YAML Ain't Markup Language", "Data format for Ansible/K8s", "Automation"),
        ac("JSON", "JavaScript Object Notation", "Structured config/data format", "Automation"),
        ac("Git", "Global Information Tracker", "Distributed version control", "Automation"),
        ac("CI/CD", "Continuous Integration/Continuous Delivery", "Automated build/deploy pipeline", "Automation"),
        ac("Docker", "Container runtime platform", "Packages apps in containers", "Automation"),
        ac("Podman", "Pod Manager", "Daemonless container engine", "Automation"),
        ac("Kubernetes", "K8s container orchestrator", "Orchestrates container workloads", "Automation"),
        ac("kubectl", "Kubernetes control CLI", "CLI for Kubernetes API", "Automation"),
        ac("Ansible", "Automation engine", "Agentless configuration management", "Automation"),
        ac("Terraform", "Infrastructure as Code tool", "Provisions cloud resources", "Automation"),
        ac("bash", "Bourne Again SHell", "Common Linux shell", "Automation"),
        ac("shebang", "#! interpreter line", "Script interpreter directive", "Automation"),
        ac("APT", "Advanced Package Tool", "Debian/Ubuntu package manager", "Management"),
        ac("DNF", "Dandified YUM", "Fedora/RHEL package manager", "Management"),
        ac("RPM", "Red Hat Package Manager", "Package format on RHEL family", "Management"),
        ac("journald", "Systemd journal daemon", "Binary system logging", "Troubleshooting"),
        ac("dmesg", "Display message", "Kernel ring buffer messages", "Troubleshooting"),
        ac("strace", "System call trace", "Traces process syscalls", "Troubleshooting"),
        ac("tcpdump", "TCP dump", "Captures network packets", "Troubleshooting"),
        ac("iptables", "IP tables firewall", "Legacy netfilter frontend", "Security"),
        ac("nftables", "Netfilter tables", "Modern netfilter framework", "Security"),
        ac("firewalld", "Dynamic firewall daemon", "Zone-based firewall on RHEL", "Security"),
        ac("GPG", "GNU Privacy Guard", "Encryption and signing tool", "Security"),
    ],
}.items():
    ACRONYMS_BY_EXAM[exam_id] = items

if __name__ == "__main__":
    partial.write_fact_banks(OUT / "comptia_fact_banks.py", FACT_BANKS)
    partial.write_acronyms(OUT / "comptia_acronyms.py", ACRONYMS_BY_EXAM)

    # Validate counts
    for exam_id, bank in FACT_BANKS.items():
        total = 0
        for domain_id, facts in bank.items():
            n = len(facts)
            alts = sum(1 for f in facts if len(f) == 5 and f[4])
            total += n + alts
        print(f"{exam_id}: ~{total} raw+alt stems across {len(bank)} domains")
    for exam_id, acr in ACRONYMS_BY_EXAM.items():
        print(f"{exam_id} acronyms: {len(acr)}")
